param(
  [string]$RepoPath='F:\TigerIQ\Workspace\tigeriq-ai-lab',
  [string]$ExecutionWorkspace='F:\TigerIQ\Workspace\tigeriq-ai-lab'
)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$ExpectedBranch='wo065/continuous-operations-v1';$Installer=Join-Path $RepoPath 'scripts\pc01-autonomy\Install-PC01-ContinuousOperations.ps1';$ControllerUrl='http://100.97.23.87:8790'
$PlannerTask='TigerIQ Autonomous Planner';$MissionTask='TigerIQ Mission Orchestrator';$ContinuousTask='TigerIQ Continuous Operations';$SupervisorTask='TigerIQ Autonomy Supervisor'
$PlannerDir='F:\TigerIQ\Runtime\autonomous-planner-v1';$Backlog=Join-Path $PlannerDir 'backlog.json';$PlannerState=Join-Path $PlannerDir 'planner-state.json';$Auth=Join-Path $PlannerDir 'authorizations.json'
$MissionDir='F:\TigerIQ\Runtime\mission-orchestrator-v1';$Inbox=Join-Path $MissionDir 'mission-inbox.json';$MissionState=Join-Path $MissionDir 'mission-state.json'
$ContinuousDir='F:\TigerIQ\Runtime\continuous-operations-v1';$Goals=Join-Path $ContinuousDir 'goals.json';$Control=Join-Path $ContinuousDir 'control.json';$ContinuousState=Join-Path $ContinuousDir 'state.json'
$SupervisorState='F:\TigerIQ\Runtime\autonomy-supervisor-v1\status.json';$EvidenceDir=Join-Path $RepoPath 'docs\evidence';$RunId=(Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ');$GoalA="e2e-a-$RunId";$GoalB="e2e-b-$RunId";$MissionA="OPS-$GoalA";$MissionB="OPS-$GoalB";$utf8=New-Object Text.UTF8Encoding($false)
function Assert($Condition,[string]$Code,[string]$Message){if(-not [bool]$Condition){throw "$Code`: $Message"}}
function JsonFile([string]$Path){if(-not(Test-Path $Path)){return $null};try{return Get-Content $Path -Raw|ConvertFrom-Json}catch{return $null}}
function Prop($Obj,[string]$Name){if($null -eq $Obj){return $null};$p=$Obj.PSObject.Properties[$Name];if($null -eq $p){return $null};return $p.Value}
function MissionRecord($State,[string]$Id){$m=Prop $State 'missions';if($null -eq $m){return $null};return Prop $m $Id}
function GoalRecord($State,[string]$Id){$g=Prop $State 'goals';if($null -eq $g){return $null};return Prop $g $Id}
function Stage($Record){$s=Prop $Record 'stage';if($null -eq $s){return 'missing'};return [string]$s}
function InboxCount([string]$Id){$i=JsonFile $Inbox;if($null -eq $i){return 0};return @($i.missions|Where-Object{$_.missionId -eq $Id}).Count}
function WriteJson([string]$Path,$Value){[IO.File]::WriteAllText($Path,($Value|ConvertTo-Json -Depth 20),$utf8)}
$files=@($Backlog,$PlannerState,$Auth,$Inbox,$MissionState,$Goals,$Control,$ContinuousState);$backup=@{};$runtimeTouched=$false
try{
  Assert ($env:COMPUTERNAME -eq 'PC01') 'WRONG_HOST' 'Continuous Operations E2E is pinned to PC01';$id=[Security.Principal.WindowsIdentity]::GetCurrent();$principal=New-Object Security.Principal.WindowsPrincipal($id);Assert ($principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) 'ADMIN_REQUIRED' 'Run PowerShell as Administrator';Assert (Test-Path $ExecutionWorkspace) 'EXECUTION_WORKSPACE_MISSING' $ExecutionWorkspace
  $git=(Get-Command git.exe -ErrorAction Stop).Source;$powershell=(Get-Command powershell.exe -ErrorAction Stop).Source;$branch=(& $git -C $RepoPath branch --show-current).Trim();Assert ($branch -eq $ExpectedBranch) 'WRONG_BRANCH' "Expected $ExpectedBranch; got $branch";$dirty=@(& $git -C $RepoPath status --porcelain);Assert ($dirty.Count -eq 0) 'REPO_NOT_CLEAN' (($dirty|Select-Object -First 10)-join '; ')
  & $powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $Installer -RepoPath $RepoPath -ExpectedBranch $ExpectedBranch -ExecutionWorkspace $ExecutionWorkspace -SkipRepositoryTests;if($LASTEXITCODE -ne 0){throw 'CONTINUOUS_INSTALLER_FAILED'};$runtimeTouched=$true
  Stop-ScheduledTask -TaskName $SupervisorTask -ErrorAction SilentlyContinue;Stop-ScheduledTask -TaskName $ContinuousTask -ErrorAction SilentlyContinue;Stop-ScheduledTask -TaskName $MissionTask -ErrorAction SilentlyContinue;Stop-ScheduledTask -TaskName $PlannerTask -ErrorAction SilentlyContinue;Start-Sleep -Seconds 2
  foreach($f in $files){if(Test-Path $f){$b="$f.pre-wo065-$RunId";Copy-Item $f $b -Force;$backup[$f]=$b}else{$backup[$f]=$null}}
  WriteJson $Backlog ([ordered]@{version=1;tasks=@()});WriteJson $Auth ([ordered]@{version=1;grants=@()});WriteJson $Inbox ([ordered]@{version=1;missions=@()});Remove-Item $PlannerState,$MissionState,$ContinuousState -Force -ErrorAction SilentlyContinue
  $queue=[ordered]@{version=1;goals=@(
    [ordered]@{goalId=$GoalA;goal='Acceptance goal A: prove safe autonomous child execution and authorization hold while Continuous Operations owns sequencing.';priority='P0';mode='acceptance';enabled=$true;dependencies=@()},
    [ordered]@{goalId=$GoalB;goal='Acceptance goal B: prove the next independent queued goal starts automatically after goal A frees the active execution slot.';priority='P1';mode='acceptance';enabled=$true;dependencies=@()}
  )};WriteJson $Goals $queue;WriteJson $Control ([ordered]@{version=1;paused=$true})
  Start-ScheduledTask -TaskName $ContinuousTask;Start-Sleep -Seconds 8;Assert ((InboxCount $MissionA) -eq 0) 'PAUSE_FAILED' 'Goal injected while paused'
  WriteJson $Control ([ordered]@{version=1;paused=$false});Start-ScheduledTask -TaskName $PlannerTask;Start-ScheduledTask -TaskName $MissionTask
  $firstDeadline=(Get-Date).AddMinutes(3);$firstReached=$false;while((Get-Date)-lt $firstDeadline){$cs=JsonFile $ContinuousState;$a=GoalRecord $cs $GoalA;$b=GoalRecord $cs $GoalB;$ms=JsonFile $MissionState;$ma=MissionRecord $ms $MissionA;Write-Host ('[{0}] WO065 | A={1} B={2} MissionA={3}' -f (Get-Date -Format 'HH:mm:ss'),(Stage $a),(Stage $b),(Stage $ma));if((Stage $ma) -eq 'waiting_authorization'){$firstReached=$true;break};if((Stage $ma) -in @('failed','blocked_plan')){throw "GOAL_A_FAILED: $(Stage $ma)"};Start-Sleep -Seconds 2};Assert $firstReached 'GOAL_A_TIMEOUT' 'Goal A did not reach waiting_authorization'
  Assert ((InboxCount $MissionA) -eq 1) 'GOAL_A_DUPLICATE' 'Goal A mission was injected more than once'
  Stop-ScheduledTask -TaskName $ContinuousTask -ErrorAction SilentlyContinue;Start-Sleep -Seconds 2;Start-ScheduledTask -TaskName $ContinuousTask;Start-Sleep -Seconds 8;Assert ((InboxCount $MissionA) -eq 1) 'RESTART_DUPLICATE' 'Restart duplicated Goal A mission'
  $secondDeadline=(Get-Date).AddMinutes(3);$secondReached=$false;while((Get-Date)-lt $secondDeadline){$cs=JsonFile $ContinuousState;$a=GoalRecord $cs $GoalA;$b=GoalRecord $cs $GoalB;$ms=JsonFile $MissionState;$mb=MissionRecord $ms $MissionB;Write-Host ('[{0}] WO065 | A={1} B={2} MissionB={3}' -f (Get-Date -Format 'HH:mm:ss'),(Stage $a),(Stage $b),(Stage $mb));if((Stage $mb) -eq 'waiting_authorization'){$secondReached=$true;break};if((Stage $mb) -in @('failed','blocked_plan')){throw "GOAL_B_FAILED: $(Stage $mb)"};Start-Sleep -Seconds 2};Assert $secondReached 'GOAL_B_TIMEOUT' 'Goal B did not start and reach waiting_authorization automatically';Assert ((InboxCount $MissionB) -eq 1) 'GOAL_B_DUPLICATE' 'Goal B mission was injected more than once'
  $ps=JsonFile $PlannerState;foreach($m in @($MissionA,$MissionB)){foreach($suffix in @('analysis-a','analysis-b','artifact','review')){$r=Prop (Prop $ps 'tasks') "$m-$suffix";Assert ((Stage $r) -eq 'done') 'SAFE_CHILD_NOT_DONE' "$m-$suffix stage=$(Stage $r)"};$red=Prop (Prop $ps 'tasks') "$m-held-red";Assert ((Stage $red) -eq 'held_authorization') 'RED_NOT_HELD' "$m red stage=$(Stage $red)";Assert ([string]::IsNullOrWhiteSpace([string](Prop $red 'controllerJobId'))) 'RED_JOB_CREATED' "$m RED hold received Controller job"}
  $status=Invoke-RestMethod -Uri "$ControllerUrl/api/v1/status" -Method Get -TimeoutSec 10;Assert ($status.ok -and $status.postgres -and $status.pc01.online -and $status.pc01.health -eq 'ok') 'PC01_BASELINE_REGRESSION' 'Controller/Postgres/PC01 unhealthy';$ops=Invoke-RestMethod -Uri 'http://127.0.0.1:11434/api/ps' -Method Get -TimeoutSec 10;$model=$ops.models|Where-Object{$_.name -eq 'qwen3:8b'}|Select-Object -First 1;Assert ($null -ne $model) 'QWEN_NOT_LOADED' 'qwen3:8b not visible';$gpuPct=if([double]$model.size -gt 0){[math]::Round(([double]$model.size_vram/[double]$model.size)*100)}else{0};Assert ($gpuPct -ge 90) 'GPU_OFFLOAD_REGRESSION' "GPU=$gpuPct%"
  Stop-ScheduledTask -TaskName $ContinuousTask -ErrorAction SilentlyContinue;Stop-ScheduledTask -TaskName $MissionTask -ErrorAction SilentlyContinue;Stop-ScheduledTask -TaskName $PlannerTask -ErrorAction SilentlyContinue;foreach($f in $files){$b=$backup[$f];if($b -and(Test-Path $b)){Move-Item $b $f -Force}else{Remove-Item $f -Force -ErrorAction SilentlyContinue}};Start-ScheduledTask -TaskName $PlannerTask;Start-ScheduledTask -TaskName $MissionTask;Start-ScheduledTask -TaskName $ContinuousTask;Start-ScheduledTask -TaskName $SupervisorTask
  $supDeadline=(Get-Date).AddSeconds(45);$sup=$null;while((Get-Date)-lt $supDeadline){$sup=JsonFile $SupervisorState;if($sup -and [bool](Prop $sup 'overallOk')){break};Start-Sleep -Seconds 2};Assert ($sup -and [bool](Prop $sup 'overallOk')) 'SUPERVISOR_NOT_HEALTHY' 'Supervisor did not recover healthy state'
  New-Item -ItemType Directory -Force -Path $EvidenceDir|Out-Null;$evidencePath=Join-Path $EvidenceDir "WO-065-CONTINUOUS-OPERATIONS-E2E-$RunId.json";$evidence=[ordered]@{scope='WO-065';runId=$RunId;host=$env:COMPUTERNAME;branch=$branch;allPass=$true;continuous=[ordered]@{task=$ContinuousTask;pauseBlockedInjection=$true;goalA=$MissionA;goalAStage='waiting_authorization';goalB=$MissionB;goalBStage='waiting_authorization';automaticNextGoal=$true;restartDuplicatePrevented=$true};runtime=[ordered]@{controller=$status.controller;postgres=$status.postgres;pc01Online=$status.pc01.online;pc01Health=$status.pc01.health;model='qwen3:8b';gpuPercent=$gpuPct;supervisorOverallOk=$true};security=[ordered]@{mainProductionTouched=$false;financialActionExecuted=$false;secretPrinted=$false}};WriteJson $evidencePath $evidence
  $rel=$evidencePath.Substring($RepoPath.Length).TrimStart('\') -replace '\\','/';& $git -C $RepoPath add -- $rel;& $git -C $RepoPath -c user.name='TigerIQ PC01' -c user.email='pc01@tigeriq.local' commit -m 'test(ops): record physical continuous operations E2E pass';if($LASTEXITCODE -ne 0){throw 'EVIDENCE_COMMIT_FAILED'};& $git -C $RepoPath push origin HEAD:refs/heads/wo065/continuous-operations-v1;$pushed=($LASTEXITCODE -eq 0)
  Write-Host '';Write-Host '============================================================';Write-Host '✅ TIGERIQ PASS — CONTINUOUS OPERATIONS V1';Write-Host 'Pause/Resume: PASS | Auto next goal: PASS | Restart: PASS | RED hold: PASS';Write-Host '============================================================';Write-Host ('TIGERIQ_CONTINUOUS_RESULT='+([ordered]@{status=if($pushed){'PHYSICAL_PASS'}else{'PHYSICAL_PASS_REMOTE_PUSH_EXTERNAL_WAIT'};allPass=$true;remotePush=$pushed;evidence=$rel;gpu="$gpuPct%"}|ConvertTo-Json -Compress))
}catch{
  try{if($runtimeTouched){Stop-ScheduledTask -TaskName $SupervisorTask -ErrorAction SilentlyContinue;Stop-ScheduledTask -TaskName $ContinuousTask -ErrorAction SilentlyContinue;Stop-ScheduledTask -TaskName $MissionTask -ErrorAction SilentlyContinue;Stop-ScheduledTask -TaskName $PlannerTask -ErrorAction SilentlyContinue};foreach($f in $files){if($backup.ContainsKey($f)){$b=$backup[$f];if($b -and(Test-Path $b)){Move-Item $b $f -Force}}};if($runtimeTouched){Start-ScheduledTask -TaskName $PlannerTask -ErrorAction SilentlyContinue;Start-ScheduledTask -TaskName $MissionTask -ErrorAction SilentlyContinue;Start-ScheduledTask -TaskName $ContinuousTask -ErrorAction SilentlyContinue;Start-ScheduledTask -TaskName $SupervisorTask -ErrorAction SilentlyContinue}}catch{};Write-Host '';Write-Host '❌ TIGERIQ WO-065 REAL BLOCKER';Write-Host ('TIGERIQ_CONTINUOUS_RESULT='+([ordered]@{status='REAL_BLOCKER';error=$_.Exception.Message;mainProductionTouched=$false;financialActionExecuted=$false;secretPrinted=$false}|ConvertTo-Json -Compress));exit 1
}
