param([string]$RepoPath='F:\TigerIQ\Workspace\tigeriq-ai-lab')
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$ExpectedBranch='wo060/mission-decomposition-v1';$Installer=Join-Path $RepoPath 'scripts\pc01-autonomy\Install-PC01-Autonomy-Final.ps1';$ControllerUrl='http://100.97.23.87:8790';$PlannerTask='TigerIQ Autonomous Planner';$MissionTask='TigerIQ Mission Orchestrator';$SupervisorTask='TigerIQ Autonomy Supervisor';$PlannerDir='F:\TigerIQ\Runtime\autonomous-planner-v1';$Backlog=Join-Path $PlannerDir 'backlog.json';$PlannerState=Join-Path $PlannerDir 'planner-state.json';$Auth=Join-Path $PlannerDir 'authorizations.json';$MissionDir='F:\TigerIQ\Runtime\mission-orchestrator-v1';$Inbox=Join-Path $MissionDir 'mission-inbox.json';$MissionState=Join-Path $MissionDir 'mission-state.json';$SupervisorState='F:\TigerIQ\Runtime\autonomy-supervisor-v1\status.json';$EvidenceDir=Join-Path $RepoPath 'docs\evidence';$RunId=(Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ');$MissionId="FINAL-$RunId"
function Assert($Condition,[string]$Code,[string]$Message){if(-not [bool]$Condition){throw "$Code`: $Message"}}
function JsonFile([string]$Path){if(-not(Test-Path $Path)){return $null};try{return Get-Content $Path -Raw|ConvertFrom-Json}catch{return $null}}
function Prop($Obj,[string]$Name){if($null -eq $Obj){return $null};$p=$Obj.PSObject.Properties[$Name];if($null -eq $p){return $null};return $p.Value}
function TaskState($Planner,[string]$Id){$tasks=Prop $Planner 'tasks';if($null -eq $tasks){return $null};return Prop $tasks $Id}
function JobId($Task){$v=Prop $Task 'controllerJobId';if($null -eq $v){return ''};return [string]$v}
$ArtifactRel=".tigeriq-runtime/autonomy-final/$MissionId-deliverable.txt";$ArtifactPath=Join-Path $RepoPath ($ArtifactRel -replace '/','\');$MissionArtifact=Join-Path $RepoPath ".tigeriq-runtime\missions\$MissionId\deliverable.txt";$BlockedArtifact=Join-Path $RepoPath ".tigeriq-runtime\missions\$MissionId\MUST_NOT_EXIST.txt"
$files=@($Backlog,$PlannerState,$Auth,$Inbox,$MissionState);$backup=@{};$installed=$false
try{
  Assert ($env:COMPUTERNAME -eq 'PC01') 'WRONG_HOST' 'Final physical E2E pinned to PC01';$id=[Security.Principal.WindowsIdentity]::GetCurrent();$principal=New-Object Security.Principal.WindowsPrincipal($id);Assert ($principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) 'ADMIN_REQUIRED' 'Run PowerShell as Administrator'
  $git=(Get-Command git.exe -ErrorAction Stop).Source;$powershell=(Get-Command powershell.exe -ErrorAction Stop).Source;$branch=(& $git -C $RepoPath branch --show-current).Trim();Assert ($branch -eq $ExpectedBranch) 'WRONG_BRANCH' "Expected $ExpectedBranch; got $branch";$dirty=@(& $git -C $RepoPath status --porcelain);Assert ($dirty.Count -eq 0) 'REPO_NOT_CLEAN' (($dirty|Select-Object -First 10)-join '; ')
  Write-Host '[FINAL] Installing consolidated PC01 autonomy runtime...';& $powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $Installer -RepoPath $RepoPath -ExpectedBranch $ExpectedBranch;if($LASTEXITCODE -ne 0){throw 'FINAL_INSTALLER_FAILED'};$installed=$true
  Stop-ScheduledTask -TaskName $SupervisorTask -ErrorAction SilentlyContinue;Stop-ScheduledTask -TaskName $MissionTask -ErrorAction SilentlyContinue;Stop-ScheduledTask -TaskName $PlannerTask -ErrorAction SilentlyContinue;Start-Sleep -Seconds 3
  foreach($f in $files){if(Test-Path $f){$b="$f.pre-final-$RunId";Copy-Item $f $b -Force;$backup[$f]=$b}else{$backup[$f]=$null}}
  Remove-Item $MissionArtifact,$BlockedArtifact,$ArtifactPath -Force -ErrorAction SilentlyContinue
  [IO.File]::WriteAllText($Backlog,'{"version":1,"tasks":[]}',(New-Object Text.UTF8Encoding($false)));[IO.File]::WriteAllText($Auth,'{"version":1,"grants":[]}',(New-Object Text.UTF8Encoding($false)));Remove-Item $PlannerState,$MissionState -Force -ErrorAction SilentlyContinue
  $mission=[ordered]@{version=1;missions=@([ordered]@{missionId=$MissionId;goal='Prove PC01 can receive one mission, decompose it, run parallel AI roles, build an artifact, review it, update closed-loop state, and hold a RED action without blocking safe work.';status='pending';priority='P0';mode='acceptance';enabled=$true})};[IO.File]::WriteAllText($Inbox,($mission|ConvertTo-Json -Depth 10),(New-Object Text.UTF8Encoding($false)))
  Start-ScheduledTask -TaskName $PlannerTask;Start-ScheduledTask -TaskName $MissionTask
  Write-Host '[FINAL] Mission injected. PC01 is now working without further operator input...'
  $deadline=(Get-Date).AddMinutes(8);$finalMission=$null;$finalPlanner=$null;do{$ms=JsonFile $MissionState;$missions=Prop $ms 'missions';$mr=if($missions){Prop $missions $MissionId}else{$null};$ps=JsonFile $PlannerState;if($mr -and ([string](Prop $mr 'stage')) -eq 'waiting_authorization'){$finalMission=$mr;$finalPlanner=$ps;break};Start-Sleep -Seconds 5}while((Get-Date)-lt $deadline)
  Assert ($null -ne $finalMission) 'MISSION_TIMEOUT' 'Mission did not reach waiting_authorization after safe child completion'
  $A="$MissionId-analysis-a";$B="$MissionId-analysis-b";$C="$MissionId-artifact";$D="$MissionId-review";$R="$MissionId-held-red";$sa=TaskState $finalPlanner $A;$sb=TaskState $finalPlanner $B;$sc=TaskState $finalPlanner $C;$sd=TaskState $finalPlanner $D;$sr=TaskState $finalPlanner $R
  foreach($pair in @(@($A,$sa),@($B,$sb),@($C,$sc),@($D,$sd))){Assert ($null -ne $pair[1] -and ([string](Prop $pair[1] 'stage')) -eq 'done') 'SAFE_CHILD_NOT_DONE' "$($pair[0]) not done"}
  Assert ($null -ne $sr -and ([string](Prop $sr 'stage')) -eq 'held_authorization') 'RED_NOT_HELD' 'RED child was not held';Assert ([string]::IsNullOrWhiteSpace((JobId $sr))) 'RED_JOB_CREATED' 'Held RED child received a Controller job';Assert (-not(Test-Path $BlockedArtifact)) 'RED_ARTIFACT_CREATED' 'Held RED action executed unexpectedly'
  Assert (Test-Path $MissionArtifact) 'MISSION_ARTIFACT_MISSING' $MissionArtifact;Assert ((Get-Content $MissionArtifact -Raw) -match 'BUILDER_PASS') 'MISSION_ARTIFACT_INVALID' 'Builder artifact did not contain PASS marker'
  $safeJobIds=@((JobId $sa),(JobId $sb),(JobId $sc),(JobId $sd));Assert (($safeJobIds|Where-Object{[string]::IsNullOrWhiteSpace($_)}).Count -eq 0) 'SAFE_JOB_ID_MISSING' 'One or more safe child jobs lack Controller job IDs'
  $status=Invoke-RestMethod -Uri "$ControllerUrl/api/v1/status" -Method Get -TimeoutSec 10;Assert ($status.ok -and $status.postgres -and $status.pc01.online -and $status.pc01.health -eq 'ok') 'PC01_BASELINE_REGRESSION' 'Controller/Postgres/PC01 unhealthy'
  $ps=Invoke-RestMethod -Uri 'http://127.0.0.1:11434/api/ps' -Method Get -TimeoutSec 10;$m=$ps.models|Where-Object{$_.name -eq 'qwen3:8b'}|Select-Object -First 1;Assert ($null -ne $m) 'QWEN_NOT_LOADED' 'qwen3:8b not visible in Ollama';$gpuPct=if([double]$m.size -gt 0){[math]::Round(([double]$m.size_vram/[double]$m.size)*100)}else{0};Assert ($gpuPct -ge 90) 'GPU_OFFLOAD_REGRESSION' "qwen3:8b GPU=$gpuPct%"
  [IO.File]::WriteAllText($ArtifactPath,"TIGERIQ FINAL AUTONOMY PASS`r`nMission=$MissionId`r`nSafeChildren=4`r`nRedHeld=1`r`nGPU=$gpuPct%",(New-Object Text.UTF8Encoding($false)))
  Stop-ScheduledTask -TaskName $MissionTask -ErrorAction SilentlyContinue;Stop-ScheduledTask -TaskName $PlannerTask -ErrorAction SilentlyContinue;Start-Sleep -Seconds 2
  foreach($f in $files){$b=$backup[$f];if($b -and (Test-Path $b)){Move-Item $b $f -Force}else{Remove-Item $f -Force -ErrorAction SilentlyContinue}}
  Remove-Item $MissionArtifact,$BlockedArtifact -Force -ErrorAction SilentlyContinue;Start-ScheduledTask -TaskName $PlannerTask;Start-ScheduledTask -TaskName $MissionTask;Start-ScheduledTask -TaskName $SupervisorTask
  $supDeadline=(Get-Date).AddSeconds(90);$sup=$null;do{$sup=JsonFile $SupervisorState;if($sup -and [bool](Prop $sup 'overallOk')){break};Start-Sleep -Seconds 3}while((Get-Date)-lt $supDeadline);Assert ($sup -and [bool](Prop $sup 'overallOk')) 'SUPERVISOR_NOT_HEALTHY' 'Supervisor did not return overallOk=true'
  New-Item -ItemType Directory -Force -Path $EvidenceDir|Out-Null;$evidencePath=Join-Path $EvidenceDir "WO-060-064-PC01-AUTONOMY-FINAL-E2E-$RunId.json";$evidence=[ordered]@{scope='WO-060..WO-064';runId=$RunId;host=$env:COMPUTERNAME;branch=$branch;allPass=$true;mission=[ordered]@{missionId=$MissionId;decomposition=$true;safeChildrenDone=4;parallelAnalysisRoles=@('Analyst A','Analyst B');builderArtifact=$true;reviewerDone=$true;closedLoopStage='waiting_authorization';redHeld=$true};runtime=[ordered]@{controller=$status.controller;postgres=$status.postgres;pc01Online=$status.pc01.online;pc01Health=$status.pc01.health;model='qwen3:8b';gpuPercent=$gpuPct;plannerTask=$PlannerTask;missionTask=$MissionTask;supervisorTask=$SupervisorTask;supervisorOverallOk=$true};security=[ordered]@{mainProductionTouched=$false;financialActionExecuted=$false;securitySensitiveActionExecuted=$false;destructiveActionExecuted=$false;secretPrinted=$false}};[IO.File]::WriteAllText($evidencePath,($evidence|ConvertTo-Json -Depth 20),(New-Object Text.UTF8Encoding($false)))
  $rel=$evidencePath.Substring($RepoPath.Length).TrimStart('\') -replace '\\','/';& $git -C $RepoPath add -- $rel;& $git -C $RepoPath -c user.name='TigerIQ PC01' -c user.email='pc01@tigeriq.local' commit -m 'test(autonomy): record final PC01 autonomous mission E2E pass';if($LASTEXITCODE -ne 0){throw 'EVIDENCE_COMMIT_FAILED'};& $git -C $RepoPath push origin HEAD:refs/heads/wo060/mission-decomposition-v1;$pushed=($LASTEXITCODE -eq 0)
  $result=[ordered]@{status=if($pushed){'DONE'}else{'PHYSICAL_DONE_REMOTE_PUSH_EXTERNAL_WAIT'};allPass=$true;missionDecomposition=$true;reviewLoop=$true;closedStateLoop=$true;authorizationBoundary=$true;supervisor24x7=$true;model='qwen3:8b';gpu="$gpuPct%";evidence=$rel;remotePush=$pushed}
  Write-Host '';Write-Host '============================================================';Write-Host '✅ TIGERIQ PASS — PC01 AUTONOMOUS RUNNING';Write-Host 'Mission -> Decompose -> Dispatch -> Build -> Review -> State -> Authorization: PASS';Write-Host 'Supervisor 24/7: PASS | qwen3:8b GPU: PASS';Write-Host '============================================================';Write-Host ('TIGERIQ_AUTONOMY_FINAL_RESULT='+($result|ConvertTo-Json -Compress))
}catch{
  try{if($installed){Stop-ScheduledTask -TaskName $SupervisorTask -ErrorAction SilentlyContinue;Stop-ScheduledTask -TaskName $MissionTask -ErrorAction SilentlyContinue;Stop-ScheduledTask -TaskName $PlannerTask -ErrorAction SilentlyContinue};foreach($f in $files){$b=$backup[$f];if($b -and (Test-Path $b)){Move-Item $b $f -Force}};Remove-Item $MissionArtifact,$BlockedArtifact,$ArtifactPath -Force -ErrorAction SilentlyContinue;if($installed){Start-ScheduledTask -TaskName $PlannerTask -ErrorAction SilentlyContinue;Start-ScheduledTask -TaskName $MissionTask -ErrorAction SilentlyContinue;Start-ScheduledTask -TaskName $SupervisorTask -ErrorAction SilentlyContinue}}catch{}
  $result=[ordered]@{status='REAL_BLOCKER';error=$_.Exception.Message;mainProductionTouched=$false;financialActionExecuted=$false;securitySensitiveActionExecuted=$false;secretPrinted=$false};Write-Host '';Write-Host '❌ TIGERIQ FINAL AUTONOMY BLOCKER';Write-Host ('TIGERIQ_AUTONOMY_FINAL_RESULT='+($result|ConvertTo-Json -Compress));exit 1
}
