param([string]$RepoPath='F:\TigerIQ\Workspace\tigeriq-ai-lab')
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$ExpectedBranch='wo058/autonomous-planner-v1';$TaskName='TigerIQ Autonomous Planner';$RuntimeDir='F:\TigerIQ\Runtime\autonomous-planner-v1';$Backlog=Join-Path $RuntimeDir 'backlog.json';$State=Join-Path $RuntimeDir 'planner-state.json';$TokenFile='F:\TigerIQ\Secrets\pc01-primary-node.ingress-token';$ControllerUrl='http://100.97.23.87:8790';$Installer=Join-Path $RepoPath 'scripts\pc01-autonomy\Install-PC01-AutonomousPlanner.ps1';$EvidenceDir=Join-Path $RepoPath 'docs\evidence';$RunId=(Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ');$ArtifactRel='.tigeriq-runtime/autonomy/WO058-AUTO-ARTIFACT.txt';$BlockedRel='.tigeriq-runtime/autonomy/WO058-SHOULD-NOT-EXIST.txt';$Artifact=Join-Path $RepoPath ($ArtifactRel -replace '/','\');$Blocked=Join-Path $RepoPath ($BlockedRel -replace '/','\')
function Assert($Condition,[string]$Code,[string]$Message){if(-not [bool]$Condition){throw "$Code`: $Message"}}
function AuthHeaders(){return @{Authorization="Bearer $([IO.File]::ReadAllText($TokenFile).Trim())"}}
function Job([string]$Id){return Invoke-RestMethod -Uri "$ControllerUrl/api/v1/work-orders/$Id" -Method Get -Headers (AuthHeaders) -TimeoutSec 15}
function PlannerState(){if(-not(Test-Path $State)){return $null};try{return Get-Content $State -Raw|ConvertFrom-Json}catch{return $null}}
$backupBacklog="$Backlog.pre-wo058-e2e";$backupState="$State.pre-wo058-e2e";$hadBacklog=Test-Path $Backlog;$hadState=Test-Path $State
try{
  Assert ($env:COMPUTERNAME -eq 'PC01') 'WRONG_HOST' 'Physical E2E pinned to PC01';$id=[Security.Principal.WindowsIdentity]::GetCurrent();$p=New-Object Security.Principal.WindowsPrincipal($id);Assert ($p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) 'ADMIN_REQUIRED' 'Run elevated'
  $git=(Get-Command git.exe -ErrorAction Stop).Source;$powershell=(Get-Command powershell.exe -ErrorAction Stop).Source;$branch=(& $git -C $RepoPath branch --show-current).Trim();Assert ($branch -eq $ExpectedBranch) 'WRONG_BRANCH' "Expected $ExpectedBranch; got $branch";$dirty=@(& $git -C $RepoPath status --porcelain);Assert ($dirty.Count -eq 0) 'REPO_NOT_CLEAN' (($dirty|Select-Object -First 10)-join '; ')
  & $powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $Installer -RepoPath $RepoPath;if($LASTEXITCODE -ne 0){throw 'INSTALLER_FAILED'}
  if($hadBacklog){Copy-Item $Backlog $backupBacklog -Force};if($hadState){Copy-Item $State $backupState -Force};Remove-Item $Artifact,$Blocked -Force -ErrorAction SilentlyContinue
  $test=[ordered]@{version=1;tasks=@(
    [ordered]@{taskId='WO058-A-ARTIFACT';title='WO058 autonomous artifact';objective='Create deterministic autonomous artifact without human action';status='pending';priority='P0';route='tool';payload=[ordered]@{toolRequest=[ordered]@{operation='write_file';path=$ArtifactRel;content='WO058_AUTONOMOUS_ARTIFACT_PASS'}};requiredCapabilities=@('filesystem','evidence');requiredPermissions=@('workspace:write','evidence:write');expectedEvidence=@('json');scopeKeys=@('autonomy/wo058/a');dependencies=@();requiresAuthorization=$false;enabled=$true;maxAttempts=1},
    [ordered]@{taskId='WO058-B-AI';title='WO058 autonomous local AI';objective='Prove planner releases a dependent local-AI job after A completes';status='pending';priority='P1';route='local_ai';payload=[ordered]@{prompt='Return only valid JSON with keys autonomous, worker and status. Values must be pass, PC01 and ok.';json=$true;temperature=0.1};requiredCapabilities=@('local_ai','evidence');requiredPermissions=@('local_ai:execute','evidence:write');expectedEvidence=@('json');scopeKeys=@('autonomy/wo058/b');dependencies=@('WO058-A-ARTIFACT');requiresAuthorization=$false;enabled=$true;maxAttempts=1},
    [ordered]@{taskId='WO058-C-AUTH';title='WO058 authorization hold';objective='This task must never execute without authorization';status='pending';priority='P0';route='tool';payload=[ordered]@{toolRequest=[ordered]@{operation='write_file';path=$BlockedRel;content='THIS_FILE_MUST_NOT_EXIST'}};requiredCapabilities=@('filesystem','evidence');requiredPermissions=@('workspace:write','evidence:write');expectedEvidence=@('json');scopeKeys=@('autonomy/wo058/c');dependencies=@();requiresAuthorization=$true;enabled=$true;maxAttempts=1}
  )}
  $test|ConvertTo-Json -Depth 20|Set-Content -Path $Backlog -Encoding UTF8;Remove-Item $State -Force -ErrorAction SilentlyContinue;Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue;Start-Sleep -Seconds 2;Start-ScheduledTask -TaskName $TaskName
  $deadline=(Get-Date).AddMinutes(6);$final=$null;do{$s=PlannerState;if($null -ne $s){$a=$s.tasks.'WO058-A-ARTIFACT';$b=$s.tasks.'WO058-B-AI';$c=$s.tasks.'WO058-C-AUTH';if($a.stage -eq 'done' -and $b.stage -eq 'done' -and $c.stage -eq 'held_authorization'){$final=$s;break}};Start-Sleep -Seconds 5}while((Get-Date)-lt $deadline)
  Assert ($null -ne $final) 'AUTONOMY_TIMEOUT' 'Planner did not reach A=done B=done C=held_authorization';Assert (Test-Path $Artifact) 'ARTIFACT_MISSING' $Artifact;Assert ([IO.File]::ReadAllText($Artifact) -eq 'WO058_AUTONOMOUS_ARTIFACT_PASS') 'ARTIFACT_INVALID' 'Autonomous artifact content mismatch';Assert (-not(Test-Path $Blocked)) 'AUTHORIZATION_GATE_BYPASSED' 'Blocked task executed';Assert ([string]::IsNullOrWhiteSpace([string]$final.tasks.'WO058-C-AUTH'.controllerJobId)) 'AUTHORIZATION_JOB_CREATED' 'Held task received a controller job'
  $aId=[string]$final.tasks.'WO058-A-ARTIFACT'.controllerJobId;$bId=[string]$final.tasks.'WO058-B-AI'.controllerJobId;Assert (-not[string]::IsNullOrWhiteSpace($aId)) 'A_JOB_ID_MISSING' 'A controller job missing';Assert (-not[string]::IsNullOrWhiteSpace($bId)) 'B_JOB_ID_MISSING' 'B controller job missing';$aJob=Job $aId;$bJob=Job $bId;Assert ($aJob.state.job.stage -eq 'done') 'A_JOB_NOT_DONE' ([string]$aJob.state.job.stage);Assert ($bJob.state.job.stage -eq 'done') 'B_JOB_NOT_DONE' ([string]$bJob.state.job.stage;)
  $metrics=$bJob.state.result.output.metrics;Assert ($metrics.model -eq 'qwen3:8b') 'AI_MODEL_FAIL' ([string]$metrics.model);Assert (([string]$metrics.processor) -match 'GPU') 'AI_GPU_FAIL' ([string]$metrics.processor);Assert ($bJob.state.result.output.parsedJson) 'AI_JSON_FAIL' 'Local AI did not produce parsed JSON'
  $status=Invoke-RestMethod -Uri "$ControllerUrl/api/v1/status" -Method Get -TimeoutSec 10;Assert ($status.ok -and $status.postgres -and $status.pc01.online -and $status.pc01.health -eq 'ok') 'BASELINE_REGRESSION' 'PC01 baseline unhealthy after autonomous E2E'
  New-Item -ItemType Directory -Force -Path $EvidenceDir|Out-Null;$evidencePath=Join-Path $EvidenceDir "WO-058-AUTONOMOUS-PLANNER-E2E-$RunId.json";$evidence=[ordered]@{workOrder='WO-058';runId=$RunId;host=$env:COMPUTERNAME;branch=$branch;allPass=$true;plannerTask=$TaskName;tests=@([ordered]@{test='A_AUTO_DISCOVER_AND_EXECUTE_TOOL';pass=$true;taskId='WO058-A-ARTIFACT';jobId=$aId;artifact=$ArtifactRel},[ordered]@{test='B_DEPENDENCY_AND_LOCAL_AI';pass=$true;taskId='WO058-B-AI';jobId=$bId;model=$metrics.model;processor=$metrics.processor},[ordered]@{test='C_AUTHORIZATION_HOLD';pass=$true;taskId='WO058-C-AUTH';controllerJobId=$null;blockedArtifactAbsent=$true},[ordered]@{test='D_PC01_BASELINE_REMAINS_HEALTHY';pass=$true;controller=$status.controller;postgres=$status.postgres;pc01=$status.pc01});mainProductionTouched=$false;secretPrinted=$false};[IO.File]::WriteAllText($evidencePath,($evidence|ConvertTo-Json -Depth 20),(New-Object Text.UTF8Encoding($false)))
  Remove-Item $Artifact,$Blocked -Force -ErrorAction SilentlyContinue
  if($hadBacklog){Move-Item $backupBacklog $Backlog -Force}else{'{"version":1,"tasks":[]}'|Set-Content -Path $Backlog -Encoding ASCII};if($hadState){Move-Item $backupState $State -Force}else{Remove-Item $State -Force -ErrorAction SilentlyContinue};Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue;Start-Sleep -Seconds 2;Start-ScheduledTask -TaskName $TaskName
  $rel=$evidencePath.Substring($RepoPath.Length).TrimStart('\') -replace '\\','/';& $git -C $RepoPath add -- $rel;& $git -C $RepoPath -c user.name='TigerIQ PC01' -c user.email='pc01@tigeriq.local' commit -m 'test(wo058): record physical autonomous planner E2E pass';if($LASTEXITCODE -ne 0){throw 'EVIDENCE_COMMIT_FAILED'};& $git -C $RepoPath push origin HEAD:refs/heads/wo058/autonomous-planner-v1;$pushed=($LASTEXITCODE -eq 0);$result=[ordered]@{status=if($pushed){'DONE'}else{'PHYSICAL_DONE_REMOTE_PUSH_EXTERNAL_WAIT'};allPass=$true;evidence=$rel;artifactAutoCreated=$true;dependentAiAutoExecuted=$true;authorizationHeld=$true;model=$metrics.model;processor=$metrics.processor;remotePush=$pushed};Write-Host ('TIGERIQ_WO058_RESULT='+($result|ConvertTo-Json -Compress))
}catch{
  try{Remove-Item $Artifact,$Blocked -Force -ErrorAction SilentlyContinue;if(Test-Path $backupBacklog){Move-Item $backupBacklog $Backlog -Force};if(Test-Path $backupState){Move-Item $backupState $State -Force};if(Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue){Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue;Start-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue}}catch{}
  $result=[ordered]@{status='REAL_BLOCKER';error=$_.Exception.Message;mainProductionTouched=$false;secretPrinted=$false};Write-Host ('TIGERIQ_WO058_RESULT='+($result|ConvertTo-Json -Compress));exit 1
}
