param([string]$RepoPath='F:\TigerIQ\Workspace\tigeriq-ai-lab',[string]$ExecutionWorkspace='F:\TigerIQ\Workspace\tigeriq-ai-lab')
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$ExpectedBranch='wo060/mission-decomposition-v1';$Installer=Join-Path $RepoPath 'scripts\pc01-autonomy\Install-PC01-Autonomy-Final.ps1';$ControllerUrl='http://100.97.23.87:8790';$PlannerTask='TigerIQ Autonomous Planner';$MissionTask='TigerIQ Mission Orchestrator';$SupervisorTask='TigerIQ Autonomy Supervisor';$PlannerLog='F:\TigerIQ\Logs\autonomous-planner-v1.log';$MissionLog='F:\TigerIQ\Logs\mission-orchestrator-v1.log';$PlannerDir='F:\TigerIQ\Runtime\autonomous-planner-v1';$Backlog=Join-Path $PlannerDir 'backlog.json';$PlannerState=Join-Path $PlannerDir 'planner-state.json';$Auth=Join-Path $PlannerDir 'authorizations.json';$MissionDir='F:\TigerIQ\Runtime\mission-orchestrator-v1';$Inbox=Join-Path $MissionDir 'mission-inbox.json';$MissionState=Join-Path $MissionDir 'mission-state.json';$SupervisorState='F:\TigerIQ\Runtime\autonomy-supervisor-v1\status.json';$EvidenceDir=Join-Path $RepoPath 'docs\evidence';$RunId=(Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ');$MissionId="FINAL-$RunId";$StartedAt=Get-Date
function Assert($Condition,[string]$Code,[string]$Message){if(-not [bool]$Condition){throw "$Code`: $Message"}}
function JsonFile([string]$Path){if(-not(Test-Path $Path)){return $null};try{return Get-Content $Path -Raw|ConvertFrom-Json}catch{return $null}}
function Prop($Obj,[string]$Name){if($null -eq $Obj){return $null};$p=$Obj.PSObject.Properties[$Name];if($null -eq $p){return $null};return $p.Value}
function TaskState($Planner,[string]$Id){$tasks=Prop $Planner 'tasks';if($null -eq $tasks){return $null};return Prop $tasks $Id}
function Stage($Task){$v=Prop $Task 'stage';if($null -eq $v){return 'pending'};return [string]$v}
function JobId($Task){$v=Prop $Task 'controllerJobId';if($null -eq $v){return ''};return [string]$v}
function TailText([string]$Path){if(-not(Test-Path $Path)){return ''};return ((Get-Content $Path -Tail 8)-join ' | ')}
$MissionArtifact=Join-Path $ExecutionWorkspace ".tigeriq-runtime\missions\$MissionId\deliverable.txt";$BlockedArtifact=Join-Path $ExecutionWorkspace ".tigeriq-runtime\missions\$MissionId\MUST_NOT_EXIST.txt";$files=@($Backlog,$PlannerState,$Auth,$Inbox,$MissionState);$backup=@{};$runtimeTouched=$false
try{
  Assert ($env:COMPUTERNAME -eq 'PC01') 'WRONG_HOST' 'Quick final is pinned to PC01';$id=[Security.Principal.WindowsIdentity]::GetCurrent();$principal=New-Object Security.Principal.WindowsPrincipal($id);Assert ($principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) 'ADMIN_REQUIRED' 'Run PowerShell as Administrator';Assert (Test-Path $ExecutionWorkspace) 'EXECUTION_WORKSPACE_MISSING' $ExecutionWorkspace
  $git=(Get-Command git.exe -ErrorAction Stop).Source;$powershell=(Get-Command powershell.exe -ErrorAction Stop).Source;$branch=(& $git -C $RepoPath branch --show-current).Trim();Assert ($branch -eq $ExpectedBranch) 'WRONG_BRANCH' "Expected $ExpectedBranch; got $branch";$dirty=@(& $git -C $RepoPath status --porcelain);Assert ($dirty.Count -eq 0) 'REPO_NOT_CLEAN' (($dirty|Select-Object -First 10)-join '; ')
  Write-Host '[FAST] Updating PC01 autonomy runtime without duplicate repository tests...';& $powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $Installer -RepoPath $RepoPath -ExpectedBranch $ExpectedBranch -ExecutionWorkspace $ExecutionWorkspace;if($LASTEXITCODE -ne 0){throw 'FINAL_INSTALLER_FAILED'};$runtimeTouched=$true
  Stop-ScheduledTask -TaskName $SupervisorTask -ErrorAction SilentlyContinue;Stop-ScheduledTask -TaskName $MissionTask -ErrorAction SilentlyContinue;Stop-ScheduledTask -TaskName $PlannerTask -ErrorAction SilentlyContinue;Start-Sleep -Seconds 2
  foreach($f in $files){if(Test-Path $f){$b="$f.pre-quick-$RunId";Copy-Item $f $b -Force;$backup[$f]=$b}else{$backup[$f]=$null}}
  Remove-Item $MissionArtifact,$BlockedArtifact -Force -ErrorAction SilentlyContinue;[IO.File]::WriteAllText($Backlog,'{"version":1,"tasks":[]}',(New-Object Text.UTF8Encoding($false)));[IO.File]::WriteAllText($Auth,'{"version":1,"grants":[]}',(New-Object Text.UTF8Encoding($false)));Remove-Item $PlannerState,$MissionState -Force -ErrorAction SilentlyContinue
  $mission=[ordered]@{version=1;missions=@([ordered]@{missionId=$MissionId;goal='Prove the installed PC01 autonomous loop can decompose, dispatch parallel AI roles, build, review, close state, and hold a RED action.';status='pending';priority='P0';mode='acceptance';enabled=$true})};[IO.File]::WriteAllText($Inbox,($mission|ConvertTo-Json -Depth 10),(New-Object Text.UTF8Encoding($false)));Start-ScheduledTask -TaskName $PlannerTask;Start-ScheduledTask -TaskName $MissionTask
  $A="$MissionId-analysis-a";$B="$MissionId-analysis-b";$C="$MissionId-artifact";$D="$MissionId-review";$R="$MissionId-held-red";$deadline=(Get-Date).AddMinutes(2);$lastDone=-1;$lastProgress=Get-Date;$finalMission=$null;$finalPlanner=$null
  while($true){
    $ms=JsonFile $MissionState;$missions=Prop $ms 'missions';$mr=if($missions){Prop $missions $MissionId}else{$null};$ps=JsonFile $PlannerState;$sa=TaskState $ps $A;$sb=TaskState $ps $B;$sc=TaskState $ps $C;$sd=TaskState $ps $D;$sr=TaskState $ps $R;$stages=@((Stage $sa),(Stage $sb),(Stage $sc),(Stage $sd));$safeDone=($stages|Where-Object{$_ -eq 'done'}).Count;$red=Stage $sr;$missionStage=if($mr){[string](Prop $mr 'stage')}else{'initializing'}
    Write-Host ('[{0}] AUTO | A={1} B={2} Build={3} Review={4} RED={5} Mission={6}' -f (Get-Date -Format 'HH:mm:ss'),$stages[0],$stages[1],$stages[2],$stages[3],$red,$missionStage)
    if($safeDone -gt $lastDone){$lastDone=$safeDone;$lastProgress=Get-Date};if($stages -contains 'failed'){throw "SAFE_CHILD_FAILED: $($stages -join ',') | PlannerLog=$(TailText $PlannerLog)"}
    if($mr -and $missionStage -eq 'waiting_authorization'){$finalMission=$mr;$finalPlanner=$ps;break}
    if(((Get-Date)-$lastProgress).TotalSeconds -ge 60){throw "NO_PROGRESS_60S: A=$($stages[0]) B=$($stages[1]) Build=$($stages[2]) Review=$($stages[3]) RED=$red | PlannerLog=$(TailText $PlannerLog) | MissionLog=$(TailText $MissionLog)"}
    if((Get-Date)-ge $deadline){throw "MISSION_TIMEOUT_120S: Mission=$missionStage | PlannerLog=$(TailText $PlannerLog) | MissionLog=$(TailText $MissionLog)"};Start-Sleep -Seconds 2
  }
  $sa=TaskState $finalPlanner $A;$sb=TaskState $finalPlanner $B;$sc=TaskState $finalPlanner $C;$sd=TaskState $finalPlanner $D;$sr=TaskState $finalPlanner $R;foreach($pair in @(@($A,$sa),@($B,$sb),@($C,$sc),@($D,$sd))){Assert ((Stage $pair[1]) -eq 'done') 'SAFE_CHILD_NOT_DONE' "$($pair[0]) stage=$(Stage $pair[1])"};Assert ((Stage $sr) -eq 'held_authorization') 'RED_NOT_HELD' "RED stage=$(Stage $sr)";Assert ([string]::IsNullOrWhiteSpace((JobId $sr))) 'RED_JOB_CREATED' 'Held RED child received a Controller job';Assert (-not(Test-Path $BlockedArtifact)) 'RED_ARTIFACT_CREATED' 'Held RED action executed';Assert (Test-Path $MissionArtifact) 'MISSION_ARTIFACT_MISSING' $MissionArtifact;Assert ((Get-Content $MissionArtifact -Raw) -match 'BUILDER_PASS') 'MISSION_ARTIFACT_INVALID' 'Builder marker missing'
  $status=Invoke-RestMethod -Uri "$ControllerUrl/api/v1/status" -Method Get -TimeoutSec 10;Assert ($status.ok -and $status.postgres -and $status.pc01.online -and $status.pc01.health -eq 'ok') 'PC01_BASELINE_REGRESSION' 'Controller/Postgres/PC01 unhealthy';$ops=Invoke-RestMethod -Uri 'http://127.0.0.1:11434/api/ps' -Method Get -TimeoutSec 10;$model=$ops.models|Where-Object{$_.name -eq 'qwen3:8b'}|Select-Object -First 1;Assert ($null -ne $model) 'QWEN_NOT_LOADED' 'qwen3:8b not visible';$gpuPct=if([double]$model.size -gt 0){[math]::Round(([double]$model.size_vram/[double]$model.size)*100)}else{0};Assert ($gpuPct -ge 90) 'GPU_OFFLOAD_REGRESSION' "GPU=$gpuPct%"
  Stop-ScheduledTask -TaskName $MissionTask -ErrorAction SilentlyContinue;Stop-ScheduledTask -TaskName $PlannerTask -ErrorAction SilentlyContinue;foreach($f in $files){$b=$backup[$f];if($b -and(Test-Path $b)){Move-Item $b $f -Force}else{Remove-Item $f -Force -ErrorAction SilentlyContinue}};Remove-Item $MissionArtifact,$BlockedArtifact -Force -ErrorAction SilentlyContinue;Start-ScheduledTask -TaskName $PlannerTask;Start-ScheduledTask -TaskName $MissionTask;Start-ScheduledTask -TaskName $SupervisorTask
  $supDeadline=(Get-Date).AddSeconds(30);$sup=$null;while($true){$sup=JsonFile $SupervisorState;if($sup -and [bool](Prop $sup 'overallOk')){break};if((Get-Date)-ge $supDeadline){throw 'SUPERVISOR_NOT_HEALTHY'};Start-Sleep -Seconds 2}
  New-Item -ItemType Directory -Force -Path $EvidenceDir|Out-Null;$evidencePath=Join-Path $EvidenceDir "WO-060-064-PC01-AUTONOMY-QUICK-FINAL-$RunId.json";$evidence=[ordered]@{scope='WO-060..WO-064';runId=$RunId;host=$env:COMPUTERNAME;branch=$branch;allPass=$true;mission=[ordered]@{missionId=$MissionId;safeChildrenDone=4;closedLoopStage='waiting_authorization';redHeld=$true};runtime=[ordered]@{codeRepo=$RepoPath;executionWorkspace=$ExecutionWorkspace;plannerIntervalMs=5000;missionIntervalMs=5000;controller=$status.controller;postgres=$status.postgres;pc01Online=$status.pc01.online;pc01Health=$status.pc01.health;model='qwen3:8b';gpuPercent=$gpuPct;supervisorOverallOk=$true};security=[ordered]@{mainProductionTouched=$false;financialActionExecuted=$false;secretPrinted=$false}};[IO.File]::WriteAllText($evidencePath,($evidence|ConvertTo-Json -Depth 20),(New-Object Text.UTF8Encoding($false)));$rel=$evidencePath.Substring($RepoPath.Length).TrimStart('\') -replace '\\','/';& $git -C $RepoPath add -- $rel;& $git -C $RepoPath -c user.name='TigerIQ PC01' -c user.email='pc01@tigeriq.local' commit -m 'test(autonomy): record quick final PC01 E2E pass';if($LASTEXITCODE -ne 0){throw 'EVIDENCE_COMMIT_FAILED'};& $git -C $RepoPath push origin HEAD:refs/heads/wo060/mission-decomposition-v1;$pushed=($LASTEXITCODE -eq 0)
  Write-Host '';Write-Host '============================================================';Write-Host '✅ TIGERIQ PASS — PC01 AUTONOMOUS RUNNING';Write-Host 'Fast loop: 5s | Mission E2E: PASS | RED held: PASS';Write-Host '============================================================';Write-Host ('TIGERIQ_AUTONOMY_FINAL_RESULT='+([ordered]@{status=if($pushed){'DONE'}else{'PHYSICAL_DONE_REMOTE_PUSH_EXTERNAL_WAIT'};allPass=$true;remotePush=$pushed;evidence=$rel;gpu="$gpuPct%"}|ConvertTo-Json -Compress))
}catch{
  try{if($runtimeTouched){Stop-ScheduledTask -TaskName $SupervisorTask -ErrorAction SilentlyContinue;Stop-ScheduledTask -TaskName $MissionTask -ErrorAction SilentlyContinue;Stop-ScheduledTask -TaskName $PlannerTask -ErrorAction SilentlyContinue};foreach($f in $files){if($backup.ContainsKey($f)){$b=$backup[$f];if($b -and(Test-Path $b)){Move-Item $b $f -Force}}};Remove-Item $MissionArtifact,$BlockedArtifact -Force -ErrorAction SilentlyContinue;if($runtimeTouched){Start-ScheduledTask -TaskName $PlannerTask -ErrorAction SilentlyContinue;Start-ScheduledTask -TaskName $MissionTask -ErrorAction SilentlyContinue;Start-ScheduledTask -TaskName $SupervisorTask -ErrorAction SilentlyContinue}}catch{};Write-Host '';Write-Host '❌ TIGERIQ QUICK FINAL BLOCKER';Write-Host ('TIGERIQ_AUTONOMY_FINAL_RESULT='+([ordered]@{status='REAL_BLOCKER';error=$_.Exception.Message;mainProductionTouched=$false;financialActionExecuted=$false;secretPrinted=$false}|ConvertTo-Json -Compress));exit 1
}
