param([string]$RepoPath='F:\TigerIQ\Workspace\tigeriq-ai-lab')
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$ExpectedBranch='wo059/authorization-engine-v1';$TaskName='TigerIQ Autonomous Planner';$RuntimeDir='F:\TigerIQ\Runtime\autonomous-planner-v1';$Backlog=Join-Path $RuntimeDir 'backlog.json';$State=Join-Path $RuntimeDir 'planner-state.json';$Authorizations=Join-Path $RuntimeDir 'authorizations.json';$TokenFile='F:\TigerIQ\Secrets\pc01-primary-node.ingress-token';$ControllerUrl='http://100.97.23.87:8790';$Installer=Join-Path $RepoPath 'scripts\pc01-autonomy\Install-PC01-AutonomousPlanner.ps1';$EvidenceDir=Join-Path $RepoPath 'docs\evidence';$RunId=(Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ')
function Assert($Condition,[string]$Code,[string]$Message){if(-not [bool]$Condition){throw "$Code`: $Message"}}
function AuthHeaders(){return @{Authorization="Bearer $([IO.File]::ReadAllText($TokenFile).Trim())"}}
function Job([string]$Id){return Invoke-RestMethod -Uri "$ControllerUrl/api/v1/work-orders/$Id" -Method Get -Headers (AuthHeaders) -TimeoutSec 15}
function PlannerState(){if(-not(Test-Path $State)){return $null};try{return Get-Content $State -Raw|ConvertFrom-Json}catch{return $null}}
function TaskState($Planner,[string]$Id){if($null -eq $Planner -or $null -eq $Planner.tasks){return $null};$p=$Planner.tasks.PSObject.Properties[$Id];if($null -eq $p){return $null};return $p.Value}
function JobIdOf($Task){if($null -eq $Task){return ''};$p=$Task.PSObject.Properties['controllerJobId'];if($null -eq $p){return ''};return [string]$p.Value}
$A="WO059-A-$RunId";$B="WO059-B-$RunId";$C="WO059-C-$RunId";$D="WO059-D-$RunId";$E="WO059-E-$RunId";$GrantId="GRANT-WO059-$RunId"
$ARel=".tigeriq-runtime/autonomy/WO059-GREEN-A-$RunId.txt";$BRel=".tigeriq-runtime/autonomy/WO059-YELLOW-BLOCKED-$RunId.txt";$CRel=".tigeriq-runtime/autonomy/WO059-YELLOW-GRANTED-$RunId.txt";$DRel=".tigeriq-runtime/autonomy/WO059-RED-BLOCKED-$RunId.txt";$ERel=".tigeriq-runtime/autonomy/WO059-GREEN-E-$RunId.txt"
$APath=Join-Path $RepoPath ($ARel -replace '/','\');$BPath=Join-Path $RepoPath ($BRel -replace '/','\');$CPath=Join-Path $RepoPath ($CRel -replace '/','\');$DPath=Join-Path $RepoPath ($DRel -replace '/','\');$EPath=Join-Path $RepoPath ($ERel -replace '/','\')
$backupBacklog="$Backlog.pre-wo059-$RunId";$backupState="$State.pre-wo059-$RunId";$backupAuth="$Authorizations.pre-wo059-$RunId";$hadBacklog=Test-Path $Backlog;$hadState=Test-Path $State;$hadAuth=Test-Path $Authorizations
try{
  Assert ($env:COMPUTERNAME -eq 'PC01') 'WRONG_HOST' 'Physical E2E pinned to PC01';$id=[Security.Principal.WindowsIdentity]::GetCurrent();$principal=New-Object Security.Principal.WindowsPrincipal($id);Assert ($principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) 'ADMIN_REQUIRED' 'Run elevated'
  $git=(Get-Command git.exe -ErrorAction Stop).Source;$powershell=(Get-Command powershell.exe -ErrorAction Stop).Source;$branch=(& $git -C $RepoPath branch --show-current).Trim();Assert ($branch -eq $ExpectedBranch) 'WRONG_BRANCH' "Expected $ExpectedBranch; got $branch";$dirty=@(& $git -C $RepoPath status --porcelain);Assert ($dirty.Count -eq 0) 'REPO_NOT_CLEAN' (($dirty|Select-Object -First 10)-join '; ')
  & $powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $Installer -RepoPath $RepoPath;if($LASTEXITCODE -ne 0){throw 'INSTALLER_FAILED'}
  if($hadBacklog){Copy-Item $Backlog $backupBacklog -Force};if($hadState){Copy-Item $State $backupState -Force};if($hadAuth){Copy-Item $Authorizations $backupAuth -Force};Remove-Item $APath,$BPath,$CPath,$DPath,$EPath -Force -ErrorAction SilentlyContinue
  $test=[ordered]@{version=1;tasks=@(
    [ordered]@{taskId=$A;title='WO059 GREEN autonomous write';objective='GREEN workspace write must auto-dispatch';status='pending';priority='P1';route='tool';payload=[ordered]@{toolRequest=[ordered]@{operation='write_file';path=$ARel;content='WO059_GREEN_AUTO_PASS'}};requiredCapabilities=@('filesystem','evidence');requiredPermissions=@('workspace:write','evidence:write');expectedEvidence=@('json');scopeKeys=@("autonomy/wo059/$A");dependencies=@();requiresAuthorization=$false;enabled=$true;maxAttempts=1},
    [ordered]@{taskId=$B;title='WO059 YELLOW hold';objective='YELLOW task without grant must stay held';status='pending';priority='P0';route='tool';actionClass='SCRIPT_EXECUTION';payload=[ordered]@{toolRequest=[ordered]@{operation='write_file';path=$BRel;content='MUST_NOT_EXIST'}};requiredCapabilities=@('filesystem','evidence');requiredPermissions=@('workspace:write','evidence:write');expectedEvidence=@('json');scopeKeys=@("autonomy/wo059/$B");dependencies=@();requiresAuthorization=$false;enabled=$true;maxAttempts=1},
    [ordered]@{taskId=$C;title='WO059 YELLOW granted';objective='Scoped active OWNER grant must release this YELLOW task only';status='pending';priority='P0';route='tool';actionClass='SCRIPT_EXECUTION';payload=[ordered]@{toolRequest=[ordered]@{operation='write_file';path=$CRel;content='WO059_YELLOW_OWNER_GRANT_PASS'}};requiredCapabilities=@('filesystem','evidence');requiredPermissions=@('workspace:write','evidence:write');expectedEvidence=@('json');scopeKeys=@("autonomy/wo059/$C");dependencies=@();requiresAuthorization=$false;enabled=$true;maxAttempts=1},
    [ordered]@{taskId=$D;title='WO059 RED hold';objective='RED financial-class task must stay held without explicit OWNER grant';status='pending';priority='P0';route='tool';actionClass='FINANCIAL';payload=[ordered]@{toolRequest=[ordered]@{operation='write_file';path=$DRel;content='MUST_NOT_EXIST'}};requiredCapabilities=@('filesystem','evidence');requiredPermissions=@('workspace:write','evidence:write');expectedEvidence=@('json');scopeKeys=@("autonomy/wo059/$D");dependencies=@();requiresAuthorization=$false;enabled=$true;maxAttempts=1},
    [ordered]@{taskId=$E;title='WO059 independent GREEN';objective='Held YELLOW/RED tasks must not block independent GREEN work';status='pending';priority='P2';route='tool';payload=[ordered]@{toolRequest=[ordered]@{operation='write_file';path=$ERel;content='WO059_HELD_DOES_NOT_BLOCK_PASS'}};requiredCapabilities=@('filesystem','evidence');requiredPermissions=@('workspace:write','evidence:write');expectedEvidence=@('json');scopeKeys=@("autonomy/wo059/$E");dependencies=@();requiresAuthorization=$false;enabled=$true;maxAttempts=1}
  )}
  $issued=(Get-Date).ToUniversalTime().AddMinutes(-1).ToString('o');$expires=(Get-Date).ToUniversalTime().AddMinutes(30).ToString('o');$grants=[ordered]@{version=1;grants=@([ordered]@{grantId=$GrantId;taskId=$C;actionClass='SCRIPT_EXECUTION';approvedBy='OWNER';issuedAt=$issued;expiresAt=$expires;revoked=$false;reason='WO059 physical scoped authorization test'})}
  [IO.File]::WriteAllText($Backlog,($test|ConvertTo-Json -Depth 20),(New-Object Text.UTF8Encoding($false)));[IO.File]::WriteAllText($Authorizations,($grants|ConvertTo-Json -Depth 10),(New-Object Text.UTF8Encoding($false)));Remove-Item $State -Force -ErrorAction SilentlyContinue;Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue;Start-Sleep -Seconds 2;Start-ScheduledTask -TaskName $TaskName
  $deadline=(Get-Date).AddMinutes(6);$final=$null;do{$s=PlannerState;$sa=TaskState $s $A;$sb=TaskState $s $B;$sc=TaskState $s $C;$sd=TaskState $s $D;$se=TaskState $s $E;if($null -ne $sa -and $null -ne $sb -and $null -ne $sc -and $null -ne $sd -and $null -ne $se -and $sa.stage -eq 'done' -and $sb.stage -eq 'held_authorization' -and $sc.stage -eq 'done' -and $sd.stage -eq 'held_authorization' -and $se.stage -eq 'done'){$final=$s;break};Start-Sleep -Seconds 5}while((Get-Date)-lt $deadline)
  Assert ($null -ne $final) 'POLICY_TIMEOUT' 'Planner did not reach GREEN done / YELLOW held+granted / RED held states';$sa=TaskState $final $A;$sb=TaskState $final $B;$sc=TaskState $final $C;$sd=TaskState $final $D;$se=TaskState $final $E
  Assert (Test-Path $APath) 'GREEN_ARTIFACT_MISSING' $APath;Assert ([IO.File]::ReadAllText($APath) -eq 'WO059_GREEN_AUTO_PASS') 'GREEN_ARTIFACT_INVALID' 'GREEN auto artifact mismatch';Assert (-not(Test-Path $BPath)) 'YELLOW_GATE_BYPASSED' 'Ungraded YELLOW artifact exists';Assert (Test-Path $CPath) 'GRANTED_ARTIFACT_MISSING' $CPath;Assert ([IO.File]::ReadAllText($CPath) -eq 'WO059_YELLOW_OWNER_GRANT_PASS') 'GRANTED_ARTIFACT_INVALID' 'Granted YELLOW artifact mismatch';Assert (-not(Test-Path $DPath)) 'RED_GATE_BYPASSED' 'RED artifact exists';Assert (Test-Path $EPath) 'INDEPENDENT_GREEN_MISSING' $EPath
  Assert ($sa.policy.riskLevel -eq 'GREEN' -and $sa.policy.decision -eq 'AUTO_DISPATCH') 'GREEN_POLICY_INVALID' ($sa.policy|ConvertTo-Json -Compress);Assert ($sb.policy.riskLevel -eq 'YELLOW' -and $sb.policy.decision -eq 'HELD_AUTHORIZATION') 'YELLOW_POLICY_INVALID' ($sb.policy|ConvertTo-Json -Compress);Assert ($sc.policy.riskLevel -eq 'YELLOW' -and $sc.policy.decision -eq 'AUTO_DISPATCH' -and $sc.policy.grantId -eq $GrantId) 'GRANT_POLICY_INVALID' ($sc.policy|ConvertTo-Json -Compress);Assert ($sd.policy.riskLevel -eq 'RED' -and $sd.policy.decision -eq 'HELD_AUTHORIZATION') 'RED_POLICY_INVALID' ($sd.policy|ConvertTo-Json -Compress)
  Assert ([string]::IsNullOrWhiteSpace((JobIdOf $sb))) 'YELLOW_JOB_CREATED' 'Held YELLOW task received a Controller job';Assert ([string]::IsNullOrWhiteSpace((JobIdOf $sd))) 'RED_JOB_CREATED' 'Held RED task received a Controller job'
  $aId=JobIdOf $sa;$cId=JobIdOf $sc;$eId=JobIdOf $se;Assert (-not[string]::IsNullOrWhiteSpace($aId)) 'A_JOB_MISSING' 'GREEN A job missing';Assert (-not[string]::IsNullOrWhiteSpace($cId)) 'C_JOB_MISSING' 'Granted C job missing';Assert (-not[string]::IsNullOrWhiteSpace($eId)) 'E_JOB_MISSING' 'Independent GREEN E job missing';foreach($jid in @($aId,$cId,$eId)){$j=Job $jid;Assert ($j.state.job.stage -eq 'done') 'JOB_NOT_DONE' "$jid stage=$($j.state.job.stage)"}
  $status=Invoke-RestMethod -Uri "$ControllerUrl/api/v1/status" -Method Get -TimeoutSec 10;Assert ($status.ok -and $status.postgres -and $status.pc01.online -and $status.pc01.health -eq 'ok') 'BASELINE_REGRESSION' 'PC01 baseline unhealthy after WO059 E2E'
  New-Item -ItemType Directory -Force -Path $EvidenceDir|Out-Null;$evidencePath=Join-Path $EvidenceDir "WO-059-AUTHORIZATION-ENGINE-E2E-$RunId.json";$evidence=[ordered]@{workOrder='WO-059';runId=$RunId;host=$env:COMPUTERNAME;branch=$branch;allPass=$true;tests=@([ordered]@{test='A_GREEN_AUTO_DISPATCH';pass=$true;taskId=$A;jobId=$aId;policy=$sa.policy},[ordered]@{test='B_YELLOW_FAIL_CLOSED';pass=$true;taskId=$B;controllerJobId=$null;policy=$sb.policy;artifactAbsent=$true},[ordered]@{test='C_SCOPED_OWNER_GRANT';pass=$true;taskId=$C;jobId=$cId;policy=$sc.policy},[ordered]@{test='D_RED_FAIL_CLOSED';pass=$true;taskId=$D;controllerJobId=$null;policy=$sd.policy;artifactAbsent=$true},[ordered]@{test='E_HELD_DOES_NOT_BLOCK_GREEN';pass=$true;taskId=$E;jobId=$eId},[ordered]@{test='F_PC01_BASELINE_HEALTHY';pass=$true;controller=$status.controller;postgres=$status.postgres;pc01=$status.pc01});mainProductionTouched=$false;financialActionExecuted=$false;securitySensitiveActionExecuted=$false;secretPrinted=$false};[IO.File]::WriteAllText($evidencePath,($evidence|ConvertTo-Json -Depth 20),(New-Object Text.UTF8Encoding($false)))
  Remove-Item $APath,$BPath,$CPath,$DPath,$EPath -Force -ErrorAction SilentlyContinue
  if($hadBacklog){Move-Item $backupBacklog $Backlog -Force}else{[IO.File]::WriteAllText($Backlog,'{"version":1,"tasks":[]}',(New-Object Text.UTF8Encoding($false)))};if($hadState){Move-Item $backupState $State -Force}else{Remove-Item $State -Force -ErrorAction SilentlyContinue};if($hadAuth){Move-Item $backupAuth $Authorizations -Force}else{[IO.File]::WriteAllText($Authorizations,'{"version":1,"grants":[]}',(New-Object Text.UTF8Encoding($false)))};Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue;Start-Sleep -Seconds 2;Start-ScheduledTask -TaskName $TaskName
  $rel=$evidencePath.Substring($RepoPath.Length).TrimStart('\') -replace '\\','/';& $git -C $RepoPath add -- $rel;& $git -C $RepoPath -c user.name='TigerIQ PC01' -c user.email='pc01@tigeriq.local' commit -m 'test(wo059): record physical authorization policy E2E pass';if($LASTEXITCODE -ne 0){throw 'EVIDENCE_COMMIT_FAILED'};& $git -C $RepoPath push origin HEAD:refs/heads/wo059/authorization-engine-v1;$pushed=($LASTEXITCODE -eq 0);$result=[ordered]@{status=if($pushed){'DONE'}else{'PHYSICAL_DONE_REMOTE_PUSH_EXTERNAL_WAIT'};allPass=$true;evidence=$rel;greenAuto=$true;yellowHeld=$true;yellowGranted=$true;redHeld=$true;independentGreenContinued=$true;remotePush=$pushed};Write-Host ('TIGERIQ_WO059_RESULT='+($result|ConvertTo-Json -Compress))
}catch{
  try{Remove-Item $APath,$BPath,$CPath,$DPath,$EPath -Force -ErrorAction SilentlyContinue;if(Test-Path $backupBacklog){Move-Item $backupBacklog $Backlog -Force};if(Test-Path $backupState){Move-Item $backupState $State -Force};if(Test-Path $backupAuth){Move-Item $backupAuth $Authorizations -Force};if(Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue){Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue;Start-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue}}catch{}
  $result=[ordered]@{status='REAL_BLOCKER';error=$_.Exception.Message;mainProductionTouched=$false;financialActionExecuted=$false;securitySensitiveActionExecuted=$false;secretPrinted=$false};Write-Host ('TIGERIQ_WO059_RESULT='+($result|ConvertTo-Json -Compress));exit 1
}
