import {readFileSync} from 'node:fs';
import {describe,expect,it} from 'vitest';

describe('#3918 API Health shared Work UI contract',()=>{
  const dashboard=readFileSync(new URL('../apps/tigeriq-core/dashboard.html',import.meta.url),'utf8');
  const core=readFileSync(new URL('../apps/tigeriq-core/core.mjs',import.meta.url),'utf8');
  const live=readFileSync(new URL('../command-center.html',import.meta.url),'utf8');
  const livePublic=readFileSync(new URL('../public/command-center.html',import.meta.url),'utf8');
  const shared=readFileSync(new URL('../public/work-ui.css',import.meta.url),'utf8');

  it('uses one shared Work UI stylesheet on Live and API Health',()=>{
    expect(dashboard).toContain('href="/work-ui.css"');
    expect(live).toContain('href="/work-ui.css"');
    expect(livePublic).toContain('href="/work-ui.css"');
    expect(shared).toContain('.work-row,.wo-card');
    expect(shared).toContain('.work-title,.wo-title');
    expect(shared).toContain('.work-summary,.wo-current');
    expect(core).toContain("url.pathname==='/work-ui.css'");
    expect(core).toContain("../../public/work-ui.css");
  });

  it('keeps API Health compact with two workforce rows and no dead top navigation',()=>{
    expect(dashboard).toContain('<body class="api-health">');
    expect(shared).toContain('.api-health .nav{display:none!important}');
    expect(shared).toContain('--employee-row-h:132px');
    expect(shared).toContain('max-height:calc(var(--employee-row-h) * 2 + var(--employee-gap) + 20px)');
    expect(shared).toContain('overflow-y:auto!important');
    expect(shared).toContain('.api-health .wo-list,.api-health .work-list{display:grid;gap:10px;grid-template-columns:repeat(2,minmax(0,1fr))');
    expect(dashboard).toContain('id="workList" class="wo-list work-list"');
    expect(dashboard).toContain('class="work-row status-');
    expect(dashboard).toContain('class="work-top"');
    expect(dashboard).toContain('class="work-title"');
    expect(dashboard).toContain('class="work-facts"');
    expect(dashboard).not.toContain('.wo-card{');
    expect(dashboard).not.toContain('class="wo-card');
    expect(dashboard).toContain('class="progress unverified"');
    expect(dashboard).toContain('class="work-next"');
    expect(dashboard).not.toContain('<div class="work-facts"><div><b>Vừa xong:</b>');
    expect(dashboard).toContain("while(/^\\[[^\\]]+\\]\\s*/.test(t))");
    expect(dashboard).toContain("'RÀ SOÁT':'REVIEW'");
    expect(dashboard).toContain("'ĐANG XỬ LÝ':'WORKING'");
    expect(dashboard).toContain("'ĐANG CHỜ':'WAITING'");
    expect(shared).toContain('/* #3918 visual parity R2');
    expect(shared).toContain('.work-row.status-review,.work-row.status-waiting,.work-row.status-verify');
    expect(shared).toContain('.work-row .state.review,.work-row .state.waiting,.work-row .state.verify');
    expect(shared).toContain('/* #3918 vivid API Health Work-card pass');
    expect(shared).toContain('.api-health .work-row.status-review');
    expect(shared).toContain('.api-health .work-row .state.review');
    expect(shared).toContain('@keyframes tiq-status-pulse');
    expect(shared).toContain('/* #3918 three-card work grid */');
    expect(shared).toContain('grid-template-columns:repeat(3,minmax(0,1fr))');
    expect(dashboard).toContain('function woProgress(x,s)');
    expect(dashboard).not.toContain('Chưa xác minh</span>');
    expect(dashboard).toContain("kind:'checks'");
    expect(dashboard).toContain("kind:'stage'");
  });

  it('orders side panels performance then recent activity then alerts and uppercases headings',()=>{
    const perf=dashboard.indexOf('HIỆU SUẤT API 24 GIỜ');
    const activity=dashboard.indexOf('HOẠT ĐỘNG GẦN ĐÂY');
    const alerts=dashboard.indexOf('CẢNH BÁO HIỆN TẠI');
    expect(perf).toBeGreaterThan(-1);
    expect(activity).toBeGreaterThan(perf);
    expect(alerts).toBeGreaterThan(activity);
    expect(dashboard).toContain('TOÀN BỘ NHÂN SỰ / TÀI NGUYÊN AI');
    expect(dashboard).toContain('DANH SÁCH CÔNG VIỆC');
  });

  it('adds live motion without forcing animation for reduced-motion users',()=>{
    expect(shared).toContain('@keyframes tiq-work-live');
    expect(shared).toContain('@keyframes tiq-event-in');
    expect(shared).toContain('@media(prefers-reduced-motion:reduce)');
    expect(dashboard).toContain("let lastActivitySignature=''");
    expect(dashboard).toContain("classList.add('recent-activity')");
    expect(dashboard).toContain('class="sync-status"');
    expect(dashboard).toContain('brand-product">API HEALTH');
    expect(dashboard).not.toContain('id="clock"');
    expect(dashboard).toContain("topLive.querySelector('b').textContent='LIVE'");
    expect(dashboard).toContain("topLive.classList.add('offline')");
    expect(shared).toContain('/* #3918 4K Health layout pass */');
    expect(shared).toContain('grid-template-columns:repeat(5,minmax(0,1fr))');
    expect(shared).toContain('grid-template-columns:repeat(4,minmax(0,1fr))');
    expect(shared).toContain('.api-health .layout{grid-template-columns:minmax(0,3.55fr) minmax(285px,.82fr)');
    expect(shared).toContain('.api-health .side .panel-h h2{font-size:14px}');
    expect(shared).toContain('/* #3918 window-responsive density pass');
    expect(shared).toContain('@media(min-width:1450px)');
    expect(shared).toContain('.api-health .workers{grid-template-columns:repeat(5,minmax(0,1fr))!important}');
    expect(shared).toContain('.api-health .wo-list,.api-health .work-list{grid-template-columns:repeat(4,minmax(0,1fr))!important}');
    expect(shared).toContain('@media(min-width:1200px) and (max-width:1449px)');
    expect(shared).toContain('@media(min-width:900px) and (max-width:1199px)');
    expect(shared).toContain('/* #3918 Work-card detail parity with LIVE');
    expect(shared).toContain('.api-health .work-row.status-review .work-title');
    expect(shared).toContain('.work-detail-backdrop');
    expect(shared).toContain('.work-detail-modal');
    expect(dashboard).toContain('id="workDetailBackdrop"');
    expect(dashboard).toContain('id="workDetailGithub"');
    expect(dashboard).toContain('function openWorkDetail(row,trigger)');
    expect(dashboard).toContain('data-work-number=');
    expect(dashboard).not.toContain('target="_blank" rel="noopener"><div class="work-main"');
    expect(shared).toContain('/* #3918 live-system activity pass */');
    expect(shared).toContain('.api-health .workforce-panel .panel-h h2');
    expect(shared).toContain('.api-health .work-panel .panel-h h2');
    expect(shared).toContain('.api-health .api-perf-panel .panel-h h2');
    expect(shared).toContain('.api-health .activity-panel .panel-h h2');
    expect(shared).toContain('.api-health .employee-live-line');
    expect(shared).toContain('@keyframes tiq-heartbeat');
    expect(shared).toContain('@keyframes tiq-worker-change');
    expect(shared).toContain('@keyframes tiq-page-scan');
    expect(dashboard).toContain('id="topLiveMeta"');
    expect(dashboard).toContain('id="workforceMeta"');
    expect(dashboard).toContain('id="activityMeta"');
    expect(dashboard).toContain('function refreshLiveUi()');
    expect(dashboard).toContain('lastCoreSuccessAt=Date.now()');
    expect(dashboard).toContain("mode=age<=5?'LIVE':age<=10?'DEGRADED':'OFFLINE'");
    expect(dashboard).toContain('employee-live-line');
    expect(dashboard).toContain('lastWorkerSignatures=new Map()');
    expect(dashboard).toContain('event cuối');
    expect(dashboard).toContain('event/phút');
  });
});
