import { describe,expect,it } from 'vitest';
import { actionable,parseBacklog,reconcile,toControllerBody,waitingDependencies,type PlannerRuntimeState } from '../apps/autonomous-planner/src/core.js';

function backlog(){return parseBacklog({version:1,tasks:[
  {taskId:'safe-p1',title:'Safe P1',objective:'write artifact',status:'pending',priority:'P1',route:'tool',payload:{toolRequest:{operation:'write_file',path:'.tigeriq-runtime/autonomy/a.txt',content:'ok'}},requiredCapabilities:[],requiredPermissions:[],expectedEvidence:['json'],scopeKeys:['autonomy/a'],dependencies:[],requiresAuthorization:false,enabled:true,maxAttempts:2},
  {taskId:'safe-p0',title:'Safe P0',objective:'analyze',status:'pending',priority:'P0',route:'local_ai',payload:{prompt:'Return JSON {"ok":true}',json:true},requiredCapabilities:[],requiredPermissions:[],expectedEvidence:['json'],scopeKeys:['autonomy/b'],dependencies:[],requiresAuthorization:false,enabled:true,maxAttempts:2},
  {taskId:'needs-auth',title:'Needs auth',objective:'must stop',status:'pending',priority:'P0',route:'tool',payload:{toolRequest:{operation:'write_file',path:'.tigeriq-runtime/autonomy/blocked.txt',content:'no'}},requiredCapabilities:[],requiredPermissions:[],expectedEvidence:['json'],scopeKeys:['autonomy/c'],dependencies:[],requiresAuthorization:true,enabled:true,maxAttempts:1},
  {taskId:'dependent',title:'Dependent',objective:'wait',status:'pending',priority:'P0',route:'deterministic',payload:{action:'resource_snapshot'},requiredCapabilities:[],requiredPermissions:[],expectedEvidence:['json'],scopeKeys:['autonomy/d'],dependencies:['safe-p1'],requiresAuthorization:false,enabled:true,maxAttempts:1}
]});}

describe('Autonomous Planner V1',()=>{
  it('holds authorization tasks and dispatches highest safe priority',()=>{const b=backlog();let state:PlannerRuntimeState={version:1,tasks:{}};state=reconcile(b,state);expect(state.tasks['needs-auth'].stage).toBe('held_authorization');expect(actionable(b,state,2).map(t=>t.taskId)).toEqual(['safe-p0','safe-p1']);});
  it('waits for dependencies then releases them after predecessor done',()=>{const b=backlog();let state:PlannerRuntimeState={version:1,tasks:{}};state=reconcile(b,state);expect(waitingDependencies(b,state)).toContain('dependent');state.tasks['safe-p1']={stage:'done',updatedAt:new Date().toISOString()};expect(actionable(b,state,4).map(t=>t.taskId)).toContain('dependent');});
  it('produces idempotent PC01 controller work order contract',()=>{const body=toControllerBody(backlog().tasks[0]);expect(body.idempotencyKey).toBe('autonomy:safe-p1:v1');expect(body.allowedWorkerKinds).toEqual(['pc01']);expect(body.independentReview).toBe(false);});
  it('rejects protected branch checkout and credential-like paths',()=>{expect(()=>parseBacklog({version:1,tasks:[{taskId:'bad',title:'bad',objective:'bad',status:'pending',priority:'P0',route:'tool',payload:{toolRequest:{operation:'git',action:'checkout',branch:'main'}},requiredCapabilities:[],requiredPermissions:[],expectedEvidence:['json'],scopeKeys:['x'],dependencies:[],requiresAuthorization:false,enabled:true,maxAttempts:1}]})).toThrow(/PROTECTED_BRANCH_DENIED/);expect(()=>parseBacklog({version:1,tasks:[{taskId:'bad2',title:'bad',objective:'bad',status:'pending',priority:'P0',route:'tool',payload:{toolRequest:{operation:'write_file',path:'secrets/token.txt',content:'x'}},requiredCapabilities:[],requiredPermissions:[],expectedEvidence:['json'],scopeKeys:['x'],dependencies:[],requiresAuthorization:false,enabled:true,maxAttempts:1}]})).toThrow(/TOOL_PATH_DENIED/);});
});
