import { describe,expect,it } from 'vitest';
import { actionable,parseBacklog,reconcile,toControllerBody,waitingDependencies,type PlannerRuntimeState } from '../apps/autonomous-planner/src/core.js';
import { evaluatePolicy,parseAuthorizationStore,type AuthorizationStore } from '../apps/autonomous-planner/src/policy.js';

const empty:AuthorizationStore={version:1,grants:[]};
const now='2026-09-03T10:00:00.000Z';
function backlog(){return parseBacklog({version:1,tasks:[
  {taskId:'safe-p1',title:'Safe P1',objective:'write artifact',status:'pending',priority:'P1',route:'tool',payload:{toolRequest:{operation:'write_file',path:'.tigeriq-runtime/autonomy/a.txt',content:'ok'}},requiredCapabilities:[],requiredPermissions:[],expectedEvidence:['json'],scopeKeys:['autonomy/a'],dependencies:[],requiresAuthorization:false,enabled:true,maxAttempts:2},
  {taskId:'safe-p0',title:'Safe P0',objective:'analyze',status:'pending',priority:'P0',route:'local_ai',payload:{prompt:'Return JSON {"ok":true}',json:true},requiredCapabilities:[],requiredPermissions:[],expectedEvidence:['json'],scopeKeys:['autonomy/b'],dependencies:[],requiresAuthorization:false,enabled:true,maxAttempts:2},
  {taskId:'needs-auth',title:'Needs auth',objective:'must stop',status:'pending',priority:'P0',route:'tool',payload:{toolRequest:{operation:'write_file',path:'.tigeriq-runtime/autonomy/blocked.txt',content:'no'}},requiredCapabilities:[],requiredPermissions:[],expectedEvidence:['json'],scopeKeys:['autonomy/c'],dependencies:[],requiresAuthorization:true,enabled:true,maxAttempts:1},
  {taskId:'dependent',title:'Dependent',objective:'wait',status:'pending',priority:'P0',route:'deterministic',payload:{action:'resource_snapshot'},requiredCapabilities:[],requiredPermissions:[],expectedEvidence:['json'],scopeKeys:['autonomy/d'],dependencies:['safe-p1'],requiresAuthorization:false,enabled:true,maxAttempts:1}
]});}

describe('Autonomous Planner authorization policy',()=>{
  it('auto-dispatches GREEN work while holding independent YELLOW work',()=>{const b=backlog();let state:PlannerRuntimeState={version:1,tasks:{}};state=reconcile(b,state,empty,now);expect(state.tasks['needs-auth'].stage).toBe('held_authorization');expect(state.tasks['needs-auth'].policy).toMatchObject({actionClass:'WORKSPACE_WRITE',riskLevel:'YELLOW',decision:'HELD_AUTHORIZATION'});expect(actionable(b,state,2).map(t=>t.taskId)).toEqual(['safe-p0','safe-p1']);});
  it('releases a YELLOW task only with an exact active OWNER grant',()=>{const b=backlog(),store=parseAuthorizationStore({version:1,grants:[{grantId:'grant-1',taskId:'needs-auth',actionClass:'WORKSPACE_WRITE',approvedBy:'OWNER',issuedAt:'2026-09-03T09:55:00Z',expiresAt:'2026-09-03T10:30:00Z',revoked:false}]});const state=reconcile(b,{version:1,tasks:{}},store,now);expect(state.tasks['needs-auth'].stage).toBe('ready');expect(state.tasks['needs-auth'].policy).toMatchObject({decision:'AUTO_DISPATCH',grantId:'grant-1'});expect(actionable(b,state,4).map(t=>t.taskId)).toContain('needs-auth');});
  it('fails closed for expired, revoked or wrong-task grants',()=>{const task=backlog().tasks.find(t=>t.taskId==='needs-auth')!;for(const grants of [[{grantId:'expired',taskId:'needs-auth',actionClass:'WORKSPACE_WRITE',approvedBy:'OWNER',issuedAt:'2026-09-03T09:00:00Z',expiresAt:'2026-09-03T09:30:00Z',revoked:false}],[{grantId:'revoked',taskId:'needs-auth',actionClass:'WORKSPACE_WRITE',approvedBy:'OWNER',issuedAt:'2026-09-03T09:00:00Z',expiresAt:'2026-09-03T11:00:00Z',revoked:true}],[{grantId:'wrong',taskId:'other-task',actionClass:'WORKSPACE_WRITE',approvedBy:'OWNER',issuedAt:'2026-09-03T09:00:00Z',expiresAt:'2026-09-03T11:00:00Z',revoked:false}]]){const store=parseAuthorizationStore({version:1,grants});expect(evaluatePolicy(task,store,now).decision).toBe('HELD_AUTHORIZATION');}});
  it('classifies explicit RED work and holds it without an OWNER grant',()=>{const b=parseBacklog({version:1,tasks:[{taskId:'money',title:'Financial',objective:'financial commitment',status:'pending',priority:'P0',route:'tool',actionClass:'FINANCIAL',payload:{toolRequest:{operation:'write_file',path:'.tigeriq-runtime/autonomy/money.txt',content:'blocked'}},requiredCapabilities:[],requiredPermissions:[],expectedEvidence:['json'],scopeKeys:['autonomy/money'],dependencies:[],requiresAuthorization:false,enabled:true,maxAttempts:1}]});const state=reconcile(b,{version:1,tasks:{}},empty,now);expect(state.tasks.money).toMatchObject({stage:'held_authorization',policy:{actionClass:'FINANCIAL',riskLevel:'RED',decision:'HELD_AUTHORIZATION'}});});
  it('denies policy downgrades from inferred higher risk actions',()=>{const b=parseBacklog({version:1,tasks:[{taskId:'script',title:'Script',objective:'execute script',status:'pending',priority:'P0',route:'tool',actionClass:'WORKSPACE_WRITE',payload:{toolRequest:{operation:'node',script:'scripts/demo.js'}},requiredCapabilities:[],requiredPermissions:[],expectedEvidence:['json'],scopeKeys:['autonomy/script'],dependencies:[],requiresAuthorization:false,enabled:true,maxAttempts:1}]});expect(()=>reconcile(b,{version:1,tasks:{}},empty,now)).toThrow(/POLICY_DOWNGRADE_DENIED/);});
  it('waits for dependencies then releases them after predecessor done',()=>{const b=backlog();let state:PlannerRuntimeState={version:1,tasks:{}};state=reconcile(b,state,empty,now);expect(waitingDependencies(b,state)).toContain('dependent');state.tasks['safe-p1']={...state.tasks['safe-p1'],stage:'done',updatedAt:now};expect(actionable(b,state,4).map(t=>t.taskId)).toContain('dependent');});
  it('produces idempotent PC01 controller work order contract',()=>{const body=toControllerBody(backlog().tasks[0]);expect(body.idempotencyKey).toBe('autonomy:safe-p1:v1');expect(body.allowedWorkerKinds).toEqual(['pc01']);expect(body.independentReview).toBe(false);});
  it('rejects invalid grants, protected branch checkout and credential-like paths',()=>{expect(()=>parseAuthorizationStore({version:1,grants:[{grantId:'x',taskId:'safe',actionClass:'WORKSPACE_WRITE',approvedBy:'AI',issuedAt:'2026-09-03T09:00:00Z',expiresAt:'2026-09-03T11:00:00Z'}]})).toThrow(/INVALID_GRANT_APPROVER/);expect(()=>parseBacklog({version:1,tasks:[{taskId:'bad',title:'bad',objective:'bad',status:'pending',priority:'P0',route:'tool',payload:{toolRequest:{operation:'git',action:'checkout',branch:'main'}},requiredCapabilities:[],requiredPermissions:[],expectedEvidence:['json'],scopeKeys:['x'],dependencies:[],requiresAuthorization:false,enabled:true,maxAttempts:1}]})).toThrow(/PROTECTED_BRANCH_DENIED/);expect(()=>parseBacklog({version:1,tasks:[{taskId:'bad2',title:'bad',objective:'bad',status:'pending',priority:'P0',route:'tool',payload:{toolRequest:{operation:'write_file',path:'secrets/token.txt',content:'x'}},requiredCapabilities:[],requiredPermissions:[],expectedEvidence:['json'],scopeKeys:['x'],dependencies:[],requiresAuthorization:false,enabled:true,maxAttempts:1}]})).toThrow(/TOOL_PATH_DENIED/);});
});
