import { describe,expect,it } from 'vitest';
import { acceptancePlan, deriveMissionStage, mergePlan, parseAiPlan, parseMissionInbox } from '../apps/mission-orchestrator/src/core.js';
import type { PlannerRuntimeState } from '../apps/autonomous-planner/src/core.js';

const mission=parseMissionInbox({version:1,missions:[{missionId:'M1',goal:'Build a safe autonomous acceptance artifact',status:'pending',priority:'P0',mode:'acceptance',enabled:true}]}).missions[0];

describe('Mission Orchestrator V1',()=>{
  it('decomposes one mission into an auditable DAG with reviewer and RED hold',()=>{const p=acceptancePlan(mission);expect(p.tasks.length).toBe(5);expect(p.tasks.filter(t=>t.dependencies.length===0).length).toBeGreaterThanOrEqual(3);expect(p.tasks.some(t=>t.title.includes('Reviewer'))).toBe(true);expect(p.tasks.some(t=>t.actionClass==='FINANCIAL')).toBe(true);expect(()=>mergePlan({version:1,tasks:[]},p)).not.toThrow();});
  it('derives waiting_authorization when safe graph is done and RED child is held',()=>{const p=acceptancePlan(mission);const s:PlannerRuntimeState={version:1,tasks:{}};for(const t of p.tasks)s.tasks[t.taskId]={stage:t.actionClass==='FINANCIAL'?'held_authorization':'done',updatedAt:new Date().toISOString()};expect(deriveMissionStage(p,s)).toBe('waiting_authorization');});
  it('validates AI-generated safe graph and rejects path escape/cycles',()=>{const good=parseAiPlan(mission,{summary:'safe',tasks:[{id:'analyze',title:'Analyze',objective:'Analyze safely',priority:'P0',route:'local_ai',dependencies:[],actionClass:'LOCAL_AI',payload:{prompt:'Return JSON',json:true}},{id:'build',title:'Build',objective:'Write safe artifact',priority:'P1',route:'tool',dependencies:['analyze'],actionClass:'WORKSPACE_WRITE',payload:{toolRequest:{operation:'write_file',path:'.tigeriq-runtime/missions/M1/out.txt',content:'ok'}}},{id:'review',title:'Review',objective:'Review result',priority:'P1',route:'local_ai',dependencies:['build'],actionClass:'LOCAL_AI',payload:{prompt:'Review JSON',json:true}}]});expect(good.tasks).toHaveLength(3);expect(()=>parseAiPlan(mission,{summary:'bad',tasks:[{id:'a',title:'A',objective:'A',route:'tool',priority:'P0',dependencies:[],payload:{toolRequest:{operation:'write_file',path:'../escape.txt',content:'x'}}},{id:'b',title:'B',objective:'B',route:'local_ai',priority:'P0',dependencies:['a'],payload:{prompt:'x'}}]})).toThrow(/PLAN_TOOL_PATH_DENIED/);expect(()=>parseAiPlan(mission,{summary:'cycle',tasks:[{id:'a',title:'A',objective:'A',route:'local_ai',priority:'P0',dependencies:['b'],payload:{prompt:'x'}},{id:'b',title:'B',objective:'B',route:'local_ai',priority:'P0',dependencies:['a'],payload:{prompt:'x'}}]})).toThrow(/PLAN_DEPENDENCY_CYCLE/);});
  it('fails closed on malformed inbox',()=>{expect(()=>parseMissionInbox({version:1,missions:[{missionId:'bad id',goal:'x'}]})).toThrow();});
});
