// @ts-nocheck
import { describe,expect,it } from 'vitest';
import { ROUTING_PROFILES,createResourceId,deriveRoutingProfile,failurePolicy,normalizeQuota,quotaUsable,rankCandidates } from '../apps/tigeriq-core/smart-router.mjs';

const base=(overrides={})=>({resource_id:'res:groq:free-model:default:core',employee_id:'NV11',provider:'groq',model:'free-model',enabled:true,health_state:'ONLINE',cooldown_until:null,cost_tier:'FREE',capabilities:['general','reasoning','review'],rank:10,success_count:9,failure_count:1,last_latency_ms:900,quota_state:{known:false,usable:true},taskStats:{general:{success:9,failure:1,retry:0,failover:0}},...overrides});

describe('#777 Smart Router foundation',()=>{
  it('exposes every required routing profile',()=>{expect(ROUTING_PROFILES).toEqual(['AUTO','CODING','FAST','CHEAP','LOCAL','RESEARCH','REVIEW']);});
  it('uses stable resource identity separate from employee identity while preserving legacy lookup shape',()=>{expect(createResourceId('Ollama','qwen3:4b','default','core')).toBe('res:ollama:qwen3-4b:default:core');expect(createResourceId('Ollama','default')).toBe('res:ollama:default');const a=base({resource_id:'res:ollama:qwen3-4b:default:core',employee_id:'NV02',provider:'ollama'});const b={...a,employee_id:'NV10'};expect(a.resource_id).toBe(b.resource_id);});
  it('derives profiles from task kind/capability without guessing unknown requests',()=>{expect(deriveRoutingProfile({capability:'coding'})).toBe('CODING');expect(deriveRoutingProfile({taskKind:'research'})).toBe('RESEARCH');expect(deriveRoutingProfile({requested:'weird'})).toBe('AUTO');});
  it('never selects paid fallback and prefers local for LOCAL',()=>{const paid=base({resource_id:'res:paid:model:default:core',provider:'paid',cost_tier:'PAID',rank:1});const local=base({resource_id:'res:ollama:qwen3-4b:default:core',employee_id:'NV10',provider:'ollama',cost_tier:'LOCAL',rank:90,last_latency_ms:5000});const remote=base();expect(rankCandidates([paid,local,remote],{profile:'AUTO'}).candidates.find(x=>x.resourceId==='res:paid:model:default:core')?.reasons).toContain('paid_fallback_forbidden');expect(rankCandidates([local,remote],{profile:'LOCAL'}).chosen?.resourceId).toBe('res:ollama:qwen3-4b:default:core');});
  it('enforces reviewer independence',()=>{const a=base();const b=base({resource_id:'res:gemini:model:default:core',employee_id:'NV12',provider:'gemini',rank:20});const d=rankCandidates([a,b],{profile:'REVIEW',capability:'review',reviewerResourceId:'res:groq:free-model:default:core'});expect(d.chosen?.resourceId).toBe('res:gemini:model:default:core');expect(d.candidates.find(x=>x.resourceId==='res:groq:free-model:default:core')?.reasons).toContain('reviewer_independence');});
  it('keeps unknown quota unknown, normalizes real request/token budgets, and blocks known cooldowns',()=>{expect(normalizeQuota({})).toMatchObject({known:false,usable:true,remainingRatio:null,requestLimit:null,requestRemaining:null,tokenLimit:null,tokenRemaining:null,sourceConfidence:'low'});expect(normalizeQuota({requestLimit:100,requestRemaining:25,tokenLimit:1000,tokenRemaining:500,sourceConfidence:'high'})).toMatchObject({known:true,remainingRatio:0.25,requestLimit:100,requestRemaining:25,tokenLimit:1000,tokenRemaining:500});expect(quotaUsable({known:true,usable:false,cooldownUntil:'2999-01-01T00:00:00Z'},Date.parse('2026-09-15T00:00:00Z'))).toBe(false);expect(rankCandidates([base({quota_state:{known:true,usable:false,resetAt:'2999-01-01T00:00:00Z'}})],{}).chosen).toBeNull();});
  it('filters active cooldown and uses task-specific latency/failure/retry/failover history',()=>{const slow=base({resource_id:'res:slow:model:default:core',provider:'slow',last_latency_ms:50,taskStats:{research:{success:1,failure:9,retry:3,failover:2,avgLatencyMs:9000}}});const fast=base({resource_id:'res:fast:model:default:core',provider:'fast',last_latency_ms:5000,taskStats:{research:{success:9,failure:1,retry:0,failover:0,avgLatencyMs:100}}});expect(rankCandidates([slow,fast],{profile:'FAST',taskKind:'research'}).chosen?.resourceId).toBe('res:fast:model:default:core');expect(rankCandidates([fast,{...slow,cooldown_until:'2999-01-01T00:00:00Z'}],{nowMs:Date.parse('2026-09-15T00:00:00Z')}).candidates.find(x=>x.resourceId==='res:slow:model:default:core')?.reasons).toContain('cooldown');});
  it('returns explainable decision evidence',()=>{const d=rankCandidates([base()],{profile:'AUTO',taskKind:'general',capability:'reasoning'});expect(d).toMatchObject({profile:'AUTO',taskKind:'general',capability:'reasoning'});expect(d.chosen?.reasons.length).toBeGreaterThan(0);expect(d.candidates[0]).toHaveProperty('score');});
  it('uses bounded failure policies and never auto-bypasses auth/config/security/paid/production boundaries',()=>{expect(failurePolicy('rate_limit')).toMatchObject({retrySameResource:false,failover:true,stop:false});expect(failurePolicy('timeout')).toMatchObject({retrySameResource:true,failover:true});expect(failurePolicy('invalid_response')).toMatchObject({failover:true,stop:false});for(const kind of ['auth','configuration','security','credential','paid','production','irreversible'])expect(failurePolicy(kind)).toMatchObject({failover:false,stop:true});});
});
