import { readFile } from 'node:fs/promises';
import { describe,expect,it } from 'vitest';
import { InMemoryOperationalStateRepository,OperationalWorkService,type DeviceRecord,type EmployeeDeviceBindingRecord,type EmployeeRecord,type JobDefinition } from '../packages/work-state/src/index.js';
const T0='2026-09-02T02:30:00.000Z';
function employee(id='EMP-ANDROID'):EmployeeRecord{return{employeeId:id,displayName:id,roles:['executor'],permissions:['job:pull','job:submit','evidence:write'],capabilities:['research.prompt'],state:'active',concurrencyLimit:1,createdAt:T0,updatedAt:T0};}
function device():DeviceRecord{return{deviceId:'DEV-ZFLIP7',platform:'android',state:'active',metadata:{},createdAt:T0,updatedAt:T0};}
function binding():EmployeeDeviceBindingRecord{return{bindingId:'BIND-1',employeeId:'EMP-ANDROID',deviceId:'DEV-ZFLIP7',state:'active',createdAt:T0,updatedAt:T0};}
function job(id='JOB-001',overrides:Partial<JobDefinition>={}):JobDefinition{return{jobId:id,idempotencyKey:`idem-${id}`,title:id,objective:'Run one verified prompt',payload:{prompt:'hello'},targetEmployeeId:'EMP-ANDROID',requiredPermissions:['job:pull','job:submit'],requiredCapabilities:['research.prompt'],allowedWorkerKinds:['device'],expectedEvidence:['json'],scopeKeys:['jobs/research'],dependencies:[],maxAttempts:2,independentReview:true,judgeRequired:true,priority:'P0',createdAt:T0,...overrides};}
async function setup(){const repo=new InMemoryOperationalStateRepository();await repo.upsertEmployee(employee());await repo.upsertDevice(device());await repo.bindDevice(binding());return{repo,service:new OperationalWorkService(repo)};}

describe('TigerIQ V1 operational work state',()=>{
  it('rejects conflicting idempotency replay',async()=>{const{service}=await setup();await service.createJob(job());await expect(service.createJob(job('JOB-002',{idempotencyKey:'idem-JOB-001',objective:'different'}))).rejects.toThrow(/idempotency conflict/i);});
  it('rejects ambiguous/traversing scopes before they can bypass locks',async()=>{const{service}=await setup();await expect(service.createJob(job('JOB-BAD',{scopeKeys:['jobs/research/../web']}))).rejects.toThrow(/scopeKey/i);});
  it('leases once, stores no raw token, rejects wrong token and blocks overlapping scope',async()=>{const{repo,service}=await setup();await service.createJob(job('JOB-A'));await service.createJob(job('JOB-B',{idempotencyKey:'idem-b',scopeKeys:['jobs/research/child']}));const lease=await service.assignNextJob({employeeId:'EMP-ANDROID',deviceId:'DEV-ZFLIP7',workerKind:'device',workerIndependenceKey:'gemini:2.5-flash',capabilities:['research.prompt'],permissions:['job:pull','job:submit'],now:T0,leaseTtlMs:60000});expect(lease?.job.jobId).toBe('JOB-A');expect(JSON.stringify([...repo.leases.values()])).not.toContain(lease!.leaseToken);expect(await service.assignNextJob({employeeId:'EMP-ANDROID',deviceId:'DEV-ZFLIP7',workerKind:'device',workerIndependenceKey:'gemini:2.5-flash',capabilities:['research.prompt'],permissions:['job:pull','job:submit'],now:T0})).toBeUndefined();await expect(service.submitResult({leaseId:lease!.leaseId,leaseToken:'wrong',acceptedAt:'2026-09-02T02:30:20.000Z',result:{jobId:'JOB-A',employeeId:'EMP-ANDROID',deviceId:'DEV-ZFLIP7',bindingId:'BIND-1',status:'completed',output:{ok:true},evidence:[{kind:'json',ref:'result://a'}],completedAt:'2026-09-02T02:30:20.000Z'}})).rejects.toThrow(/token/i);});
  it('recovers expired lease after restart and bounds retry',async()=>{const{repo,service}=await setup();await service.createJob(job('JOB-R',{maxAttempts:1}));const lease=await service.assignNextJob({employeeId:'EMP-ANDROID',deviceId:'DEV-ZFLIP7',workerKind:'device',workerIndependenceKey:'gemini:2.5-flash',capabilities:['research.prompt'],permissions:['job:pull','job:submit'],now:T0,leaseTtlMs:15000});expect(lease).toBeDefined();const restarted=new OperationalWorkService(repo);const recovered=await restarted.recoverAfterRestart('2026-09-02T02:31:00.000Z');expect(recovered).toEqual({expiredLeases:1,requeuedJobs:0,terminalJobs:1});expect((await repo.getJob('JOB-R'))?.job.stage).toBe('failed');});
  it('does not reach DONE until evidence, reviewer and judge gates pass',async()=>{const{repo,service}=await setup();await service.createJob(job());const lease=await service.assignNextJob({employeeId:'EMP-ANDROID',deviceId:'DEV-ZFLIP7',workerKind:'device',workerIndependenceKey:'gemini:2.5-flash',capabilities:['research.prompt'],permissions:['job:pull','job:submit'],now:T0,leaseTtlMs:60000});await expect(service.submitResult({leaseId:lease!.leaseId,leaseToken:lease!.leaseToken,acceptedAt:'2026-09-02T02:30:10.000Z',result:{jobId:'JOB-001',employeeId:'EMP-ANDROID',deviceId:'DEV-ZFLIP7',bindingId:'BIND-1',status:'completed',output:{text:'x'},evidence:[{kind:'text',ref:'wrong-kind'}],completedAt:'2026-09-02T02:30:10.000Z'}})).rejects.toThrow(/expected evidence/i);await service.submitResult({leaseId:lease!.leaseId,leaseToken:lease!.leaseToken,acceptedAt:'2026-09-02T02:30:11.000Z',result:{jobId:'JOB-001',employeeId:'EMP-ANDROID',deviceId:'DEV-ZFLIP7',bindingId:'BIND-1',status:'completed',output:{text:'x'},evidence:[{kind:'json',ref:'result://job-001'}],completedAt:'2026-09-02T02:30:11.000Z'}});expect((await repo.getJob('JOB-001'))?.job.stage).toBe('reviewing');await expect(service.recordReview({jobId:'JOB-001',role:'reviewer',reviewerId:'REV-ALIAS',independenceKey:'gemini:2.5-flash',verdict:'pass',conclusion:'same identity',evidence:[{kind:'text',ref:'review'}],reviewedAt:'2026-09-02T02:30:12.000Z'})).rejects.toThrow(/independent/i);await service.recordReview({jobId:'JOB-001',role:'reviewer',reviewerId:'REV-1',independenceKey:'anthropic:claude',verdict:'pass',conclusion:'pass',evidence:[{kind:'text',ref:'review'}],reviewedAt:'2026-09-02T02:30:12.000Z'});expect((await repo.getJob('JOB-001'))?.job.stage).toBe('judging');await service.recordReview({jobId:'JOB-001',role:'judge',reviewerId:'JUDGE-1',independenceKey:'openai:gpt',verdict:'pass',conclusion:'pass',evidence:[{kind:'text',ref:'judge'}],reviewedAt:'2026-09-02T02:30:13.000Z'});expect((await repo.getJob('JOB-001'))?.job.stage).toBe('done');});
  it('migration defines normalized PostgreSQL production state and atomic leasing',async()=>{const sql=await readFile('db/migrations/001_operational_state_v1.sql','utf8');const repository=await readFile('packages/work-state/src/postgres-repository.ts','utf8');for(const table of ['employees','devices','ai_providers','jobs','leases','results','evidence','prompts','reviews','prompt_metrics'])expect(sql).toContain(`CREATE TABLE IF NOT EXISTS ${table}`);expect(repository).toMatch(/FOR UPDATE SKIP LOCKED/i);expect(repository).toMatch(/pg_advisory_xact_lock/i);expect(sql).toContain('lease_token_hash');expect(sql).not.toMatch(/\blease_token\s+text/i);});
});
