import { createHash, randomBytes, randomUUID, timingSafeEqual } from 'node:crypto';
import type { EvidenceInput, JobDefinition, JobResultInput } from './types.js';

export function sha256(value:string):string { return createHash('sha256').update(value,'utf8').digest('hex'); }
export function stableJson(value:unknown):string { if(Array.isArray(value)) return `[${value.map(stableJson).join(',')}]`; if(value&&typeof value==='object'){const record=value as Record<string,unknown>;return `{${Object.keys(record).sort().map(k=>`${JSON.stringify(k)}:${stableJson(record[k])}`).join(',')}}`;} return JSON.stringify(value); }
export function normalizeScope(scope:string):string { const normalized=scope.trim().replaceAll('\\','/').replace(/\/+$/,'').toLowerCase(); if(!normalized||normalized.startsWith('/')||/^[a-z]:\//.test(normalized)) return ''; const segments=normalized.split('/'); if(segments.some(s=>!s||s==='.'||s==='..')) return ''; return segments.join('/'); }
export function normalizeIndependenceKey(value:string):string { const normalized=value.trim().toLowerCase(); if(!normalized) throw new Error('worker independence key is required'); return normalized; }
export function jobSignature(job:JobDefinition):string { return sha256(stableJson({goalId:job.goalId,title:job.title,objective:job.objective,payload:job.payload,targetEmployeeId:job.targetEmployeeId,preferredProviderId:job.preferredProviderId,requiredPermissions:[...job.requiredPermissions].sort(),requiredCapabilities:[...job.requiredCapabilities].sort(),allowedWorkerKinds:[...job.allowedWorkerKinds].sort(),expectedEvidence:[...job.expectedEvidence].sort(),scopeKeys:job.scopeKeys.map(normalizeScope).sort(),dependencies:[...job.dependencies].sort(),maxAttempts:job.maxAttempts,independentReview:job.independentReview,judgeRequired:job.judgeRequired,priority:job.priority})); }
export function resultSignature(result:JobResultInput):string { return sha256(stableJson({jobId:result.jobId,employeeId:result.employeeId,deviceId:result.deviceId,bindingId:result.bindingId,status:result.status,output:result.output,evidence:result.evidence,failure:result.failure})); }
export function validateJobDefinition(job:JobDefinition):void { for(const [name,value] of [['jobId',job.jobId],['idempotencyKey',job.idempotencyKey],['title',job.title],['objective',job.objective]] as const) if(!value.trim()) throw new Error(`${name} is required`); if(!Number.isInteger(job.maxAttempts)||job.maxAttempts<1||job.maxAttempts>10) throw new Error('maxAttempts must be between 1 and 10'); if(job.scopeKeys.length===0) throw new Error('scopeKeys is required'); for(const scope of job.scopeKeys) if(!normalizeScope(scope)) throw new Error(`invalid scopeKey ${scope}`); if(job.expectedEvidence.length===0) throw new Error('expectedEvidence is required'); if(job.judgeRequired&&!job.independentReview) throw new Error('judgeRequired requires independentReview'); if(!Number.isFinite(Date.parse(job.createdAt))) throw new Error('createdAt must be an ISO date'); }
export function validateEvidence(evidence:EvidenceInput[]):void { for(const item of evidence){ if(!item.ref.trim()) throw new Error('evidence ref is required'); if(item.sha256&&!/^[a-f0-9]{64}$/i.test(item.sha256)) throw new Error('evidence sha256 must be 64 hex characters'); } }
export function assertExpectedEvidence(expected:string[],evidence:EvidenceInput[]):void { validateEvidence(evidence); for(const kind of expected) if(!evidence.some(item=>item.kind===kind)) throw new Error(`missing expected evidence ${kind}`); }
export function scopesConflict(left:string[],right:string[]):boolean { return left.some(a=>right.some(b=>a===b||a.startsWith(`${b}/`)||b.startsWith(`${a}/`))); }
export function issueLeaseToken():{leaseToken:string;leaseTokenHash:string} { const leaseToken=randomBytes(32).toString('base64url'); return {leaseToken,leaseTokenHash:sha256(leaseToken)}; }
export function newId(prefix:string):string { return `${prefix}-${randomUUID()}`.toUpperCase(); }
export function safeHashEqual(leftHex:string,rightHex:string):boolean { const left=Buffer.from(leftHex,'hex'); const right=Buffer.from(rightHex,'hex'); return left.length===right.length&&timingSafeEqual(left,right); }
