import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const html=readFileSync('public/web-v1/index.html','utf8');
const app=readFileSync('public/web-v1/app.js','utf8');
const adapter=readFileSync('public/web-v1/company-control-tower-adapter.js','utf8');
const mock=readFileSync('public/web-v1/mock-data.js','utf8');
const client=readFileSync('public/web-v1/controller-client.js','utf8');
const config=JSON.parse(readFileSync('vercel.json','utf8'));
for(const label of ['COMPANY CONTROL TOWER','MỤC TIÊU QUAN TRỌNG NHẤT','KẾT QUẢ KINH DOANH','MISSION ĐANG CHẠY','CẦN SẾP','KẾT QUẢ VỪA HOÀN TẤT','SỨC KHỎE QUY TRÌNH','Vận hành kỹ thuật'])assert.match(html,new RegExp(label.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));
for(const id of ['homeKpis','businessMetrics','homeMissions','homeOwnerActions','homeOutcomes','homeProcesses','buildFacts','jobBoard','providerGrid','promptGrid'])assert.match(html,new RegExp(`id="${id}"`));
assert.equal(config.rewrites.find(row=>row.source==='/')?.destination,'/web-v1/index.html');
assert.match(client,/\/api\/web\/v1\/snapshot/);assert.match(client,/\/api\/workforce\/status/);
assert.doesNotMatch(app,/api\.github\.com|\/api\/web-control-status|\/api\/auto-work/);
assert.match(adapter,/BUSINESS_CONTRACT_PENDING/);assert.match(adapter,/PREVIEW_ONLY/);
assert.match(mock,/authoritative:\s*false/);assert.match(mock,/MẪU COMPANY-001/);assert.match(mock,/availability:\s*'unavailable'/);
console.log('COMPANY_CONTROL_TOWER_UI_PASS');
