import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const html=readFileSync('public/web-v1/index.html','utf8');
const app=readFileSync('public/web-v1/app.js','utf8');
const client=readFileSync('public/web-v1/controller-client.js','utf8');
const mock=readFileSync('public/web-v1/mock-data.js','utf8');
const config=JSON.parse(readFileSync('vercel.json','utf8'));
for(const label of ['WEB CONTROL V1','Bảng điều hành công ty','Giao mục tiêu','Công việc','Phòng ban & nhân sự','AI đang dùng','Prompt Architect','Kết quả & kiểm tra','Lỗi & khôi phục','Nhật ký','Kết nối'])assert.match(html,new RegExp(label.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));
for(const id of ['progressRing','departmentGrid','employeeGrid','providerGrid','jobBoard','resultList','checkTable','recoveryGrid','activityTimeline'])assert.match(html,new RegExp(`id="${id}"`));
assert.equal(config.rewrites.find(row=>row.source==='/')?.destination,'/web-v1/index.html');
assert.match(client,/\/api\/web\/v1\/snapshot/);assert.match(client,/\/api\/workforce\/status/);assert.doesNotMatch(client,/x-tigeriq-admin-secret.*=/);assert.doesNotMatch(app,/api\.github\.com|\/api\/web-control-status|\/api\/auto-work/);assert.match(mock,/authoritative:\s*false/);assert.match(mock,/departments:\s*\[/);assert.match(mock,/checks:\s*\[/);console.log('WEB_CONTROL_V1_COMPANY_DASHBOARD_PASS');
