import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const html = readFileSync('public/index.html', 'utf8');
assert.match(html, /id="instruction"/);
assert.match(html, /id="dispatch"/);
assert.match(html, /operation:'work-board'/);
assert.match(html, /operation:'work-order'/);
assert.match(html, /TigerIQ AI Lab · Command Center/);
assert.match(html, /Giao việc cho Vy/);
console.log('WO017_WORK_BOARD_UI_PASS');
