from pathlib import Path


def replace_once(text, old, new, label):
    if old not in text:
        raise SystemExit(f'missing patch anchor: {label}')
    return text.replace(old, new, 1)

control_path = Path('api/control.mjs')
control = control_path.read_text(encoding='utf-8')

old_stage = """export function issueStage(issue, comments = []) {\n  const bodies = Array.isArray(comments) ? comments.map((x) => String(x?.body || x || '')) : [];\n  if (bodies.some((x) => x.includes('TIGERIQ_PC01_FAILED') || x.includes('TIGERIQ_JOB_FAILED'))) return 'failed';\n  if (issue?.state === 'closed' || bodies.some((x) => x.includes('TIGERIQ_PC01_DONE') || x.includes('TIGERIQ_PC01_RESULT') || x.includes('TIGERIQ_JOB_DONE') || x.includes('TIGERIQ_JOB_RESULT'))) return 'completed';\n  if (bodies.some((x) => x.includes('TIGERIQ_PC01_CLAIMED') || x.includes('TIGERIQ_JOB_CLAIMED'))) return 'claimed';\n  return 'queued';\n}\n"""
new_stage = """export function issueEvidenceSummary(comments = []) {\n  const bodies = Array.isArray(comments) ? comments.map((x) => String(x?.body || x || '')) : [];\n  return {\n    claimed: bodies.some((x) => x.includes('TIGERIQ_PC01_CLAIMED') || x.includes('TIGERIQ_JOB_CLAIMED') || x.includes('TIGERIQ_COMMAND_CLAIMED')),\n    result: bodies.some((x) => x.includes('TIGERIQ_PC01_DONE') || x.includes('TIGERIQ_PC01_RESULT') || x.includes('TIGERIQ_JOB_DONE') || x.includes('TIGERIQ_JOB_RESULT') || x.includes('TIGERIQ_COMMAND_RESULT')),\n    failed: bodies.some((x) => x.includes('TIGERIQ_PC01_FAILED') || x.includes('TIGERIQ_JOB_FAILED') || x.includes('TIGERIQ_COMMAND_FAILED')),\n    reviewPass: bodies.some((x) => x.includes('REVIEW_PASS')),\n    judgePass: bodies.some((x) => x.includes('JUDGE_PASS')),\n  };\n}\n\nexport function issueStage(issue, comments = []) {\n  const evidence = issueEvidenceSummary(comments);\n  if (evidence.failed) return 'failed';\n  if (issue?.state === 'closed' && ['not_planned', 'duplicate'].includes(String(issue?.state_reason || ''))) return 'cancelled';\n  if (evidence.result || issue?.state === 'closed') return 'completed';\n  if (evidence.claimed) return 'claimed';\n  return 'queued';\n}\n"""
control = replace_once(control, old_stage, new_stage, 'issueStage')

old_status = """  const stage = issueStage(issue, comments);\n  return {\n    ok: true,\n    issue: {\n      number: issue.number,\n      title: issue.title,\n      state: issue.state,\n      stage,\n      url: issue.html_url,\n      updatedAt: issue.updated_at,\n      comments: Array.isArray(comments) ? comments.length : 0,\n    },\n  };\n}\n"""
new_status = """  const stage = issueStage(issue, comments);\n  const evidence = issueEvidenceSummary(comments);\n  return {\n    ok: true,\n    issue: {\n      number: issue.number,\n      title: issue.title,\n      state: issue.state,\n      stateReason: issue.state_reason || null,\n      stage,\n      url: issue.html_url,\n      updatedAt: issue.updated_at,\n      comments: Array.isArray(comments) ? comments.length : 0,\n      evidence,\n    },\n  };\n}\n"""
control = replace_once(control, old_status, new_status, 'workOrderStatus')
control = replace_once(control, "      workOrderStatusTracking: true,\n", "      workOrderStatusTracking: true,\n      workOrderLifecycleEvidence: true,\n", 'capability')
control_path.write_text(control, encoding='utf-8')

verify_path = Path('scripts/verify_queue_hygiene.mjs')
verify = verify_path.read_text(encoding='utf-8')
verify = verify.replace("import { normalizeInstruction, workFingerprint, issueStage } from '../api/control.mjs';", "import { normalizeInstruction, workFingerprint, issueStage, issueEvidenceSummary } from '../api/control.mjs';")
verify = replace_once(verify, "assert.equal(issueStage({ state: 'closed' }, []), 'completed');\n", "assert.equal(issueStage({ state: 'closed' }, []), 'completed');\nassert.equal(issueStage({ state: 'closed', state_reason: 'not_planned' }, []), 'cancelled');\nassert.equal(issueStage({ state: 'closed', state_reason: 'duplicate' }, []), 'cancelled');\n", 'cancelled tests')
verify = replace_once(verify, "assert.equal(issueStage({ state: 'open' }, [{ body: 'TIGERIQ_JOB_FAILED reason' }]), 'failed');\n", "assert.equal(issueStage({ state: 'open' }, [{ body: 'TIGERIQ_JOB_FAILED reason' }]), 'failed');\nassert.deepEqual(issueEvidenceSummary([{ body: 'TIGERIQ_JOB_CLAIMED\\nREVIEW_PASS' }, { body: 'TIGERIQ_JOB_RESULT PASS\\nJUDGE_PASS' }]), { claimed: true, result: true, failed: false, reviewPass: true, judgePass: true });\n", 'evidence test')
verify_path.write_text(verify, encoding='utf-8')

index_path = Path('public/index.html')
index = index_path.read_text(encoding='utf-8')
index = replace_once(index, '<meta name="color-scheme" content="dark" />\n<title>TigerIQ AI</title>', '<meta name="color-scheme" content="dark" />\n<meta name="theme-color" content="#0b0f16" />\n<meta name="apple-mobile-web-app-capable" content="yes" />\n<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />\n<meta name="apple-mobile-web-app-title" content="TigerIQ AI" />\n<link rel="manifest" href="/manifest.webmanifest" />\n<title>TigerIQ AI</title>', 'pwa head')
index = replace_once(index, "const stateText={online:'Trực tuyến',offline:'Ngắt kết nối',working:'Đang làm việc',degraded:'Suy giảm',unknown:'Chưa xác định'};const typeText={command:'Lệnh','work-order':'Công việc'};const issueStateText={open:'Đang mở',closed:'Đã đóng'};", "const stateText={online:'Trực tuyến',offline:'Ngắt kết nối',working:'Đang làm việc',degraded:'Suy giảm',unknown:'Chưa xác định'};const typeText={command:'Lệnh','work-order':'Công việc'};const issueStateText={open:'Đang mở',closed:'Đã đóng'};const stageText={queued:'Đang chờ',claimed:'Đang thực thi',completed:'Hoàn tất',failed:'Thất bại',cancelled:'Đã hủy'};const trackedKey='tigeriq_tracked_work_orders';", 'stage constants')

anchor = "function chatContext(){return [...messages.querySelectorAll('.bubble')].slice(-14).map(x=>({role:x.classList.contains('user')?'user':'assistant',content:String(x.dataset.raw||'').slice(0,2000)})).filter(x=>x.content)}\n"
tracking = """function chatContext(){return [...messages.querySelectorAll('.bubble')].slice(-14).map(x=>({role:x.classList.contains('user')?'user':'assistant',content:String(x.dataset.raw||'').slice(0,2000)})).filter(x=>x.content)}\nfunction loadTracked(){try{const x=JSON.parse(localStorage.getItem(trackedKey)||'[]');return Array.isArray(x)?x.slice(-12):[]}catch{return []}}\nfunction saveTracked(rows){localStorage.setItem(trackedKey,JSON.stringify(rows.slice(-12)))}\nfunction trackIssue(issue){if(!issue?.number)return;const rows=loadTracked().filter(x=>Number(x.number)!==Number(issue.number));rows.push({number:Number(issue.number),title:String(issue.title||''),url:String(issue.url||''),stage:'queued',updatedAt:Date.now()});saveTracked(rows)}\nfunction evidenceLabel(e){const p=[];if(e?.reviewPass)p.push('Review PASS');if(e?.judgePass)p.push('Judge PASS');return p.length?' · '+p.join(' · '):''}\nasync function pollTracked(showStable=false){const rows=loadTracked();if(!rows.length)return;let changed=false;for(const row of rows){if(['completed','failed','cancelled'].includes(row.stage)&&!showStable)continue;try{const d=await api({operation:'work-order-status',issueNumber:row.number});const next=d.issue?.stage||row.stage;if(next!==row.stage){row.stage=next;row.updatedAt=Date.now();changed=true;addBubble(`Công việc #${row.number}: ${stageText[next]||next}${evidenceLabel(d.issue?.evidence)}.`,'assistant','TigerIQ AI · theo dõi tự động')}else if(showStable){addBubble(`Công việc #${row.number}: ${stageText[next]||next}${evidenceLabel(d.issue?.evidence)}.`,'assistant','TigerIQ AI · trạng thái công việc')}}catch{}}if(changed)saveTracked(rows)}\n"""
index = replace_once(index, anchor, tracking, 'tracking helpers')

old_send_tail = """const b=addBubble(d.reply||'Đã nhận.','assistant',meta);if(d.issue?.url){const a=document.createElement('a');a.href=d.issue.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Mở công việc #'+d.issue.number;a.style.display='block';a.style.marginTop='8px';b.append(a)}}catch(e){"""
new_send_tail = """const b=addBubble(d.reply||'Đã nhận.','assistant',meta);if(d.issue?.url){trackIssue(d.issue);const a=document.createElement('a');a.href=d.issue.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Mở công việc #'+d.issue.number;a.style.display='block';a.style.marginTop='8px';b.append(a);setTimeout(()=>pollTracked(false),1200)}}catch(e){"""
index = replace_once(index, old_send_tail, new_send_tail, 'track created work order')

old_canary = """async function canary(){const token=tokenInput.value.trim();if(!token){addBubble('PC01 hiện được theo dõi từ bằng chứng GitHub hiện có. Để tạo một bài kiểm tra mới, cần kết nối GitHub một lần.','assistant','TigerIQ AI');await refresh(true);openSettings();return}addBubble('Đang tạo bài kiểm tra PC01...','assistant','TigerIQ AI');try{const d=await api({operation:'canary'});addBubble(`Đã tạo kiểm tra PC01 #${d.issue.number}. Em sẽ theo dõi kết quả qua hàng đợi GitHub.`,'assistant','TigerIQ AI');await refresh(false)}catch(e){addBubble('Không tạo được kiểm tra PC01: '+(e.details||e.message),'assistant','TigerIQ AI')}}\n"""
new_canary = """async function canary(){try{const d=await api({operation:'work-order-status',issueNumber:58});const s=d.issue?.stage||'queued';addBubble(`PC01 canary #58: ${stageText[s]||s}${evidenceLabel(d.issue?.evidence)}. Em không tạo thêm canary trùng.`,'assistant','TigerIQ AI · PC01')}catch(e){addBubble('Chưa lấy được bằng chứng PC01: '+(e.details||e.message),'assistant','TigerIQ AI')}}\n"""
index = replace_once(index, old_canary, new_canary, 'canonical canary only')

old_boot = "restoreHistory();refresh(false);if(tokenInput.value)testGithub();\n"
new_boot = "restoreHistory();refresh(false);pollTracked(false);setInterval(()=>pollTracked(false),30000);if(tokenInput.value)testGithub();if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});\n"
index = replace_once(index, old_boot, new_boot, 'boot tracking')
index_path.write_text(index, encoding='utf-8')

Path('public/manifest.webmanifest').write_text('''{\n  "name": "TigerIQ AI",\n  "short_name": "TigerIQ AI",\n  "description": "Trợ lý điều hành TigerIQ AI",\n  "start_url": "/",\n  "scope": "/",\n  "display": "standalone",\n  "background_color": "#0b0f16",\n  "theme_color": "#0b0f16",\n  "lang": "vi",\n  "icons": [{"src":"/tigeriq-icon.svg","sizes":"any","type":"image/svg+xml","purpose":"any maskable"}]\n}\n''', encoding='utf-8')
Path('public/tigeriq-icon.svg').write_text('''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><rect width="512" height="512" rx="112" fill="#0b0f16"/><text x="256" y="350" text-anchor="middle" font-size="300">🐯</text></svg>\n''', encoding='utf-8')
Path('public/sw.js').write_text('''self.addEventListener('install',()=>self.skipWaiting());\nself.addEventListener('activate',event=>event.waitUntil(self.clients.claim()));\nself.addEventListener('fetch',event=>{if(event.request.method==='GET')event.respondWith(fetch(event.request));});\n''', encoding='utf-8')

print('WO015_PATCH_APPLIED')
