param([string]$RepoPath='F:\TigerIQ\Workspace\tigeriq-ai-lab')
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$ControllerUrl='http://100.97.23.87:8790';$OllamaUrl='http://127.0.0.1:11434';$ControllerTask='TigerIQ Workforce Controller';$WorkerTask='TigerIQ PC01 Native Worker';$TokenFile='F:\TigerIQ\Secrets\pc01-primary-node.ingress-token';$RunId=(Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ');$started=(Get-Date).ToUniversalTime();$results=@()
function Assert([bool]$Condition,[string]$Code,[string]$Message){if(-not $Condition){throw "$Code`: $Message"}}
function Pass([string]$Name,[object]$Evidence){$script:results += [ordered]@{test=$Name;pass=$true;evidence=$Evidence}}
function Token(){Assert (Test-Path $TokenFile) 'TOKEN_MISSING' 'Ingress token missing';return [IO.File]::ReadAllText($TokenFile).Trim()}
function Headers(){return @{Authorization="Bearer $(Token)"}}
function Status(){return Invoke-RestMethod -Uri "$ControllerUrl/api/v1/status" -Method Get -TimeoutSec 10}
function Create-Job([hashtable]$Body){$json=$Body|ConvertTo-Json -Depth 12 -Compress;return Invoke-RestMethod -Uri "$ControllerUrl/api/v1/work-orders" -Method Post -Headers (Headers) -ContentType 'application/json' -Body $json -TimeoutSec 15}
function Job-State([string]$JobId){return Invoke-RestMethod -Uri "$ControllerUrl/api/v1/work-orders/$JobId" -Method Get -Headers (Headers) -TimeoutSec 10}
function Wait-Job([string]$JobId,[string[]]$Terminal=@('done','failed'),[int]$Seconds=180){$deadline=(Get-Date).AddSeconds($Seconds);do{$state=Job-State $JobId;if($Terminal -contains $state.state.job.stage){return $state};Start-Sleep -Milliseconds 750}while((Get-Date)-lt $deadline);throw "JOB_TIMEOUT: $JobId"}
function Ai-Body([string]$Suffix,[string]$Prompt){return @{idempotencyKey="wo057-$RunId-$Suffix";title="WO057 E2E AI $Suffix";objective=$Prompt;payload=@{route='local_ai';taskType='ai';prompt=$Prompt;json=$true;temperature=0.1};requiredCapabilities=@('local_ai','evidence');requiredPermissions=@('local_ai:execute','evidence:write');allowedWorkerKinds=@('pc01');expectedEvidence=@('json');scopeKeys=@("e2e/$RunId/$Suffix");maxAttempts=1;independentReview=$false;judgeRequired=$false;priority='P1'}}
function Evidence-Doc([object]$State){$ref=@($State.state.evidence|Where-Object{$_.kind -eq 'json'}|Select-Object -First 1).ref;Assert (-not [string]::IsNullOrWhiteSpace($ref)) 'EVIDENCE_REF_MISSING' 'JSON evidence reference missing';$full=Join-Path $RepoPath ($ref -replace '/','\');Assert (Test-Path $full) 'EVIDENCE_FILE_MISSING' $full;return Get-Content $full -Raw|ConvertFrom-Json}
function Wait-Online([int]$Seconds=90){$deadline=(Get-Date).AddSeconds($Seconds);do{try{$s=Status;if($s.ok -and $s.postgres -and $s.pc01 -and $s.pc01.online){return $s}}catch{};Start-Sleep -Seconds 2}while((Get-Date)-lt $deadline);throw 'RECOVERY_TIMEOUT: PC01 did not become online'}

Assert ($env:COMPUTERNAME -eq 'PC01') 'WRONG_HOST' 'Physical E2E is pinned to PC01'
Assert (Test-Path $RepoPath) 'REPO_MISSING' $RepoPath

# TEST A — Health
$status=Status;Assert ($status.ok -and $status.postgres) 'TEST_A_CONTROLLER_POSTGRES_FAIL' 'Controller/PostgreSQL unhealthy';$tags=Invoke-RestMethod -Uri "$OllamaUrl/api/tags" -Method Get -TimeoutSec 10;Assert (@($tags.models.name) -contains 'qwen3:8b') 'TEST_A_OLLAMA_FAIL' 'qwen3:8b unavailable';Assert ($status.pc01 -and $status.pc01.online -and $status.pc01.health -eq 'ok') 'TEST_A_WORKER_FAIL' 'PC01 Worker not healthy';Pass 'A_HEALTH' @{controller=$status.controller;postgres=$status.postgres;ollama='qwen3:8b';pc01=$status.pc01}

# TEST B — Workforce
Assert ([int]$status.workforce.employees -ge 1) 'TEST_B_EMPLOYEE_FAIL' 'employees < 1';Assert ([int]$status.workforce.devices -ge 1) 'TEST_B_DEVICE_FAIL' 'devices < 1';Pass 'B_WORKFORCE' $status.workforce

# TEST C — Local AI
$prompt='Phân tích trạng thái hệ thống TigerIQ hiện tại và chỉ trả JSON hợp lệ gồm summary, risks, next_actions.';$created=Create-Job (Ai-Body 'local-ai' $prompt);$state=Wait-Job $created.workOrder.jobId;Assert ($state.state.job.stage -eq 'done') 'TEST_C_STAGE_FAIL' "stage=$($state.state.job.stage)";$metrics=$state.state.result.output.metrics;Assert ($metrics.model -eq 'qwen3:8b') 'TEST_C_MODEL_FAIL' 'wrong model';Assert ([string]$metrics.processor -match 'GPU') 'TEST_C_GPU_FAIL' "processor=$($metrics.processor)";Assert ($state.state.result.output.parsedJson) 'TEST_C_JSON_FAIL' 'parsedJson missing';Pass 'C_LOCAL_AI' @{jobId=$created.workOrder.jobId;stage=$state.state.job.stage;metrics=$metrics;evidence=$state.state.evidence}

# TEST D — Tool execution read + artifact write + deterministic validation
$fixtureRel=".tigeriq-runtime/e2e/$RunId/fixture.txt";$artifactRel=".tigeriq-runtime/e2e/$RunId/artifact.txt";$fixture=Join-Path $RepoPath ($fixtureRel -replace '/','\');New-Item -ItemType Directory -Force -Path (Split-Path $fixture -Parent)|Out-Null;[IO.File]::WriteAllText($fixture,'TIGERIQ_FIXTURE_PASS',(New-Object Text.UTF8Encoding($false)))
$toolBody=@{idempotencyKey="wo057-$RunId-tool";title='WO057 E2E Tool';objective='Read fixture then create deterministic artifact';payload=@{route='tool';toolRequests=@(@{operation='read_file';path=$fixtureRel},@{operation='write_file';path=$artifactRel;content='TIGERIQ_TOOL_ARTIFACT_PASS'})};requiredCapabilities=@('filesystem','evidence');requiredPermissions=@('workspace:read','workspace:write','evidence:write');allowedWorkerKinds=@('pc01');expectedEvidence=@('json');scopeKeys=@("e2e/$RunId/tool");maxAttempts=1;independentReview=$false;judgeRequired=$false;priority='P1'}
$created=Create-Job $toolBody;$toolState=Wait-Job $created.workOrder.jobId;Assert ($toolState.state.job.stage -eq 'done') 'TEST_D_STAGE_FAIL' "stage=$($toolState.state.job.stage)";$artifact=Join-Path $RepoPath ($artifactRel -replace '/','\');Assert (Test-Path $artifact) 'TEST_D_ARTIFACT_MISSING' $artifact;Assert ([IO.File]::ReadAllText($artifact) -eq 'TIGERIQ_TOOL_ARTIFACT_PASS') 'TEST_D_ARTIFACT_INVALID' 'artifact content mismatch';Pass 'D_TOOL_EXECUTION' @{jobId=$created.workOrder.jobId;artifact=$artifactRel;commands=$toolState.state.result.output.results;evidence=$toolState.state.evidence}

# TEST E — Safe intentional failure
$failBody=@{idempotencyKey="wo057-$RunId-failure";title='WO057 E2E Intentional Failure';objective='Verify safe failure capture';payload=@{route='tool';toolRequest=@{operation='read_file';path=".tigeriq-runtime/e2e/$RunId/does-not-exist.txt"}};requiredCapabilities=@('filesystem','evidence');requiredPermissions=@('workspace:read','evidence:write');allowedWorkerKinds=@('pc01');expectedEvidence=@('json');scopeKeys=@("e2e/$RunId/failure");maxAttempts=1;independentReview=$false;judgeRequired=$false;priority='P1'}
$created=Create-Job $failBody;$failState=Wait-Job $created.workOrder.jobId;Assert ($failState.state.job.stage -eq 'failed') 'TEST_E_STAGE_FAIL' "stage=$($failState.state.job.stage)";Assert ($failState.state.result.status -eq 'failed') 'TEST_E_RESULT_FAIL' 'result did not capture failure';Assert ($failState.state.result.failure) 'TEST_E_ERROR_MISSING' 'failure details missing';Pass 'E_FAILURE_HANDLING' @{jobId=$created.workOrder.jobId;failure=$failState.state.result.failure;evidence=$failState.state.evidence}

# TEST F — Exactly two simultaneous local AI jobs; static scheduler limit is 2
$j1=Create-Job (Ai-Body 'concurrency-1' 'Return JSON {"job":1,"status":"ok"}.');$j2=Create-Job (Ai-Body 'concurrency-2' 'Return JSON {"job":2,"status":"ok"}.');$s1=Wait-Job $j1.workOrder.jobId;$s2=Wait-Job $j2.workOrder.jobId;Assert ($s1.state.job.stage -eq 'done' -and $s2.state.job.stage -eq 'done') 'TEST_F_STAGE_FAIL' 'one concurrency job failed';$d1=Evidence-Doc $s1;$d2=Evidence-Doc $s2;$overlap=([datetime]$d1.started_at -lt [datetime]$d2.completed_at) -and ([datetime]$d2.started_at -lt [datetime]$d1.completed_at);Assert $overlap 'TEST_F_NOT_CONCURRENT' 'AI execution intervals did not overlap';Pass 'F_CONCURRENCY' @{jobs=@($j1.workOrder.jobId,$j2.workOrder.jobId);overlap=$overlap;configuredLocalAiMax=2;intervals=@(@($d1.started_at,$d1.completed_at),@($d2.started_at,$d2.completed_at))}

# TEST G — Safe service restart recovery + post-recovery work order
Stop-ScheduledTask -TaskName $WorkerTask -ErrorAction Stop;Stop-ScheduledTask -TaskName $ControllerTask -ErrorAction Stop;Start-Sleep -Seconds 3;Start-ScheduledTask -TaskName $ControllerTask;Start-Sleep -Seconds 3;Start-ScheduledTask -TaskName $WorkerTask;$recovered=Wait-Online 120;$recoveryJob=Create-Job (Ai-Body 'recovery' 'Return JSON {"recovery":"pass"}.');$recoveryState=Wait-Job $recoveryJob.workOrder.jobId;Assert ($recoveryState.state.job.stage -eq 'done') 'TEST_G_POST_RECOVERY_JOB_FAIL' "stage=$($recoveryState.state.job.stage)";Pass 'G_RECOVERY' @{pc01=$recovered.pc01;jobId=$recoveryJob.workOrder.jobId;stage=$recoveryState.state.job.stage}

$completed=(Get-Date).ToUniversalTime();$evidence=[ordered]@{workOrder='WO-057';runId=$RunId;host=$env:COMPUTERNAME;startedAt=$started.ToString('o');completedAt=$completed.ToString('o');branch=(& git -C $RepoPath branch --show-current).Trim();headSha=(& git -C $RepoPath rev-parse HEAD).Trim();tests=$results;allPass=(@($results|Where-Object{-not $_.pass}).Count -eq 0);mainProductionTouched=$false;openClawDependency=$false}
$evidenceDir=Join-Path $RepoPath 'docs\evidence';New-Item -ItemType Directory -Force -Path $evidenceDir|Out-Null;$evidencePath=Join-Path $evidenceDir "WO-057-PC01-PRIMARY-NODE-E2E-$RunId.json";$evidence|ConvertTo-Json -Depth 20|Set-Content -Path $evidencePath -Encoding UTF8
$evidence|Add-Member -NotePropertyName evidencePath -NotePropertyValue $evidencePath;$evidence|ConvertTo-Json -Depth 20 -Compress
