import { timingSafeEqual, randomUUID } from 'node:crypto';
import { modelRouterStatus, routeModel } from './model-router.mjs';

const REPO = process.env.TIGERIQ_REPO || 'newsdayads/tigeriq-ai-lab';
const COMMAND_SECRET = process.env.TIGERIQ_COMMAND_SECRET || '';
const GITHUB_TOKEN = process.env.TIGERIQ_GITHUB_TOKEN || '';
const CANARY_ISSUE = Number(process.env.TIGERIQ_PC01_CANARY_ISSUE || '58');
const ALLOWED_PRIORITIES = new Set(['P0', 'P1', 'P2']);
function json(res,status,body){res.statusCode=status;res.setHeader('content-type','application/json; charset=utf-8');res.setHeader('cache-control','no-store');res.setHeader('x-content-type-options','nosniff');res.setHeader('x-frame-options','DENY');res.setHeader('referrer-policy','no-referrer');res.end(JSON.stringify(body));}
function safeEqual(left,right){const a=Buffer.from(String(left||''));const b=Buffer.from(String(right||''));return a.length===b.length&&a.length>0&&timingSafeEqual(a,b);}
function authorizedByServerSecret(req){return Boolean(COMMAND_SECRET&&safeEqual(req.headers['x-tigeriq-secret'],COMMAND_SECRET));}
function clientGithubToken(req){const v=req.headers['x-tigeriq-github-token'];return typeof v==='string'?v.trim():'';}
function writeCredential(req){const c=clientGithubToken(req);if(c)return{token:c,mode:'client-token'};if(GITHUB_TOKEN&&authorizedByServerSecret(req))return{token:GITHUB_TOKEN,mode:'server-token'};throw Object.assign(new Error('github_authorization_required'),{status:401});}
async function readBody(req){const chunks=[];let total=0;for await(const chunk of req){const p=Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk);total+=p.length;if(total>32768)throw new Error('payload_too_large');chunks.push(p);}return chunks.length?JSON.parse(Buffer.concat(chunks).toString('utf8')):{};}
function repoParts(){const[owner,repo]=REPO.split('/');if(!owner||!repo)throw new Error('invalid_repo');return{owner,repo};}
async function gh(path,init={},token=''){const headers={accept:'application/vnd.github+json','x-github-api-version':'2022-11-28','user-agent':'tigeriq-ai-vercel-control',...(init.headers||{})};if(token)headers.authorization=`Bearer ${token}`;const response=await fetch(`https://api.github.com${path}`,{...init,headers});const text=await response.text();let data=null;try{data=text?JSON.parse(text):null;}catch{data={message:text.slice(0,500)};}if(!response.ok)throw Object.assign(new Error(`github_${response.status}`),{status:response.status,details:data});return data;}
async function statusSnapshot(token=''){const{owner,repo}=repoParts();const[repoInfo,openIssues,canary,comments]=await Promise.all([gh(`/repos/${owner}/${repo}`,{},token),gh(`/repos/${owner}/${repo}/issues?state=open&per_page=50&sort=updated&direction=desc`,{},token),gh(`/repos/${owner}/${repo}/issues/${CANARY_ISSUE}`,{},token).catch(()=>null),gh(`/repos/${owner}/${repo}/issues/${CANARY_ISSUE}/comments?per_page=100`,{},token).catch(()=>[])]);const jobs=openIssues.filter(i=>!i.pull_request&&typeof i.body==='string'&&(i.body.includes('TIGERIQ_JOB_V1')||i.body.includes('TIGERIQ_COMMAND_V1'))).slice(0,20).map(i=>({number:i.number,title:i.title,state:i.state,updatedAt:i.updated_at,url:i.html_url,type:i.body.includes('TIGERIQ_COMMAND_V1')?'command':'work-order'}));const bodies=Array.isArray(comments)?comments.map(x=>String(x.body||'')):[];const claimed=bodies.some(x=>x.includes('TIGERIQ_PC01_CLAIMED'));const terminal=bodies.some(x=>x.includes('TIGERIQ_PC01_DONE')||x.includes('TIGERIQ_PC01_RESULT'));const failed=bodies.some(x=>x.includes('TIGERIQ_PC01_FAILED'));const pc01=terminal?'online':claimed?'working':failed?'degraded':'offline';return{ok:true,generatedAt:new Date().toISOString(),controlPlane:{vercel:'online',github:'online',repository:repoInfo.full_name,serverWriteConfigured:Boolean(GITHUB_TOKEN&&COMMAND_SECRET),clientTokenSupported:true,ai:modelRouterStatus()},execution:{pc01,openclaw:'unknown',ollama:'unknown',canaryIssue:CANARY_ISSUE,canaryState:canary?.state||'unknown'},queue:{count:jobs.length,jobs}};}
async function githubIdentity(token){if(!token)throw Object.assign(new Error('github_authorization_required'),{status:401});const{owner,repo}=repoParts();const[user,repoInfo]=await Promise.all([gh('/user',{},token),gh(`/repos/${owner}/${repo}`,{},token)]);return{ok:true,login:user.login,repository:repoInfo.full_name,repositoryAccess:true};}
async function createWorkOrder(payload,token){const instruction=String(payload.instruction||payload.message||'').trim();const priority=String(payload.priority||'P1').toUpperCase();if(instruction.length<3||instruction.length>4000)throw new Error('invalid_instruction');if(!ALLOWED_PRIORITIES.has(priority))throw new Error('invalid_priority');const id=randomUUID();const titleText=instruction.replace(/\s+/g,' ').slice(0,72);const body=['TIGERIQ_JOB_V1','','## Instruction',instruction,'','## Priority',priority,'','## Source','vercel-chat','','## Request ID',id].join('\n');const{owner,repo}=repoParts();const issue=await gh(`/repos/${owner}/${repo}/issues`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:`[${priority}] [TigerIQ AI] ${titleText}`,body})},token);return{ok:true,requestId:id,issue:{number:issue.number,url:issue.html_url,title:issue.title}};}
async function createCanary(token){const id=`vercel-canary-${Date.now()}-${randomUUID().slice(0,8)}`;const body=`TIGERIQ_COMMAND_V1\n\`\`\`json\n${JSON.stringify({idempotency_key:id,action:'system.status',args:{}},null,2)}\n\`\`\``;const{owner,repo}=repoParts();const issue=await gh(`/repos/${owner}/${repo}/issues`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:`[P0] PC01 Web Control canary ${new Date().toISOString()}`,body})},token);return{ok:true,idempotencyKey:id,issue:{number:issue.number,url:issue.html_url}};}
function classifyChat(message){const text=String(message||'').trim().toLowerCase();if(!text)return'invalid';if(/(trạng thái|status|đang chạy|online|pc01.*(sao|thế nào|trạng thái)|github.*(sao|thế nào)|vercel.*(sao|thế nào))/.test(text))return'status';if(/(làm được gì|làm đc gì|có thể làm gì|khả năng|giúp được gì|giúp đc gì)/.test(text))return'capabilities';if(/^(làm|thực hiện|triển khai|tạo|sửa|fix|cập nhật|kiểm tra pc01)\b/.test(text))return'work-order';return'conversation';}
function capabilitiesReply(snapshot){const pc=snapshot.execution.pc01==='online'?'đang trực tuyến':snapshot.execution.pc01==='working'?'đang làm việc':'chưa nhận lệnh ổn định';return`Web Control và GitHub đang trực tuyến. Em có thể nhận công việc, tạo Work Order trên GitHub, theo dõi hàng đợi và kiểm tra PC01. PC01 hiện ${pc}.`;}
async function aiConversation(message){const result=await routeModel('chief',[{role:'system',content:'Bạn là Chief of Staff của TigerIQ AI. Trả lời tiếng Việt, ngắn gọn, chính xác. Không tuyên bố đã thực hiện hành động nếu không có evidence. Nếu người dùng muốn thực thi, hướng dẫn họ bắt đầu câu bằng “Làm” để tạo Work Order.'},{role:'user',content:String(message).slice(0,4000)}]);return{ok:true,mode:'ai',reply:result.text,evidence:result.evidence};}
export default async function handler(req,res){try{if(req.method==='GET')return json(res,200,await statusSnapshot(clientGithubToken(req)));if(req.method!=='POST')return json(res,405,{error:'method_not_allowed'});const payload=await readBody(req);const operation=String(payload.operation||'status');const optionalToken=clientGithubToken(req);if(operation==='status')return json(res,200,await statusSnapshot(optionalToken));if(operation==='whoami')return json(res,200,await githubIdentity(writeCredential(req).token));if(operation==='chat'){const kind=classifyChat(payload.message);if(kind==='invalid')return json(res,400,{error:'invalid_message'});if(kind==='status'){const snapshot=await statusSnapshot(optionalToken);return json(res,200,{ok:true,mode:'status',reply:`Vercel: trực tuyến · GitHub: trực tuyến · PC01: ${snapshot.execution.pc01==='online'?'trực tuyến':snapshot.execution.pc01==='working'?'đang làm việc':'chưa sẵn sàng'} · Hàng đợi: ${snapshot.queue.count} công việc.`,snapshot});}if(kind==='capabilities'){const snapshot=await statusSnapshot(optionalToken);return json(res,200,{ok:true,mode:'capabilities',reply:capabilitiesReply(snapshot),snapshot});}if(kind==='conversation')return json(res,200,await aiConversation(payload.message));const result=await createWorkOrder(payload,writeCredential(req).token);return json(res,201,{...result,mode:'work-order',reply:`Đã tạo công việc #${result.issue.number} trên GitHub. TigerIQ AI sẽ theo dõi trạng thái thực thi và evidence.`});}if(operation==='work-order')return json(res,201,await createWorkOrder(payload,writeCredential(req).token));if(operation==='canary')return json(res,201,await createCanary(writeCredential(req).token));return json(res,400,{error:'unsupported_operation'});}catch(error){const name=error instanceof Error?error.message:String(error);let status=Number(error?.status)||502;if(name==='payload_too_large')status=413;else if(name.startsWith('invalid_'))status=400;else if(name==='github_authorization_required'||name==='github_401')status=401;else if(name==='github_403')status=403;return json(res,status,{error:name,details:error?.details?.message||undefined});}}
